In [132]:
# import pdfplumber
import pandas as pd
import numpy as np
import nltk
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.corpus import stopwords 
from string import punctuation
from nltk.corpus import wordnet as wn
from nltk.stem import WordNetLemmatizer
from nltk.probability import FreqDist
from heapq import nlargest
from collections import defaultdict
import pandas as pd 
from nltk.collocations import *
# nltk.download('punkt')
# nltk.download('stopwords')
# nltk.download('wordnet')

In [133]:
# Import CV
f=open('textfile.txt','r', errors = 'ignore')
text=f.read()

In [134]:
def nlp(x):
    word_sent = word_tokenize(x.lower().replace("\n",""))
    _stopwords = set(stopwords.words('english') + list(punctuation)+list("●")+list('–')+list('’'))
    word_sent=[word for word in word_sent if word not in _stopwords]
    lemmatizer = WordNetLemmatizer()
    NLP_Processed_CV = [lemmatizer.lemmatize(word) for word in word_tokenize(" ".join(word_sent))]
#     return " ".join(NLP_Processed_CV)
    return NLP_Processed_CV

In [135]:
def get_key_word(x):
    finder = BigramCollocationFinder.from_words(x)
    lst = []
    Key_word_from_CV = []
    for i in sorted(finder.ngram_fd.items()):
    # if a double word appears more than once, then print it out.
        if i[1] > 1:
            print(i)
            lst.append(i[0])
        else:
            pass

    # print("************************")
    for j in lst:
    #     print(" ".join(j))
        Key_word_from_CV.append(" ".join(j))
    return Key_word_from_CV

In [136]:
NLP_Processed_CV = nlp(text)
# NLP_Processed_CV=' '.join(NLP_Processed_CV)
NLP_Processed_CV

['rakshit',
 'khajuriamachine',
 'learning',
 'engineertalab',
 'tillo',
 'gole',
 'gujral',
 '180002',
 'jammu',
 'india',
 'rakshitraina1234',
 'gmail.com',
 '914955615514',
 'aug',
 '2001',
 'http',
 '//www.linkedin.com/in/rakshit-khajuria-3627781b8/',
 'http',
 '//github.com/ryzxxl9149556155summaryskilled',
 'developing',
 'implementing',
 'data-driven',
 'solution',
 'real-world',
 'problem',
 'utilizing',
 'range',
 'tool',
 'andtechniques',
 'extract',
 'valuable',
 'insight',
 'large',
 'complex',
 'data',
 'set',
 'posse',
 'diverse',
 'experience',
 'cleaningand',
 'analyzing',
 'data',
 'enhancing',
 'existing',
 'model',
 'continuously',
 'seeking',
 'enhance',
 'skill',
 'broaden',
 'myknowledge',
 'dynamic',
 '\x00eld',
 'data',
 'science.skillstools',
 'python',
 'git',
 'github',
 'jupyter',
 'notebook',
 'anaconda',
 'v',
 'codepackages',
 'scikit-learn',
 'numpy',
 'panda',
 'matplotlib',
 'nltk',
 'tensorflow',
 'flask',
 'streamlit',
 'spacy',
 'text',
 'blob',
 'vader.machine',
 'learning',
 'supervised',
 'learning',
 'unsupervised',
 'learning',
 'clustering',
 'algorithm',
 'decision',
 'tree',
 'randomforests',
 'neural',
 'networks.nlp',
 'sentiment',
 'analysis',
 'text',
 'classi\x00cation',
 'named',
 'entity',
 'recognition',
 'word',
 'embedding',
 'topic',
 'modeling',
 'deeplearning',
 'nlp',
 'model',
 'e.g',
 '.',
 'transformer',
 'bert',
 'lstms',
 'soft',
 'skillstime',
 'management',
 'problem-solving',
 'leadership',
 'teamwork',
 'presentation',
 'skill',
 'con\x00denceprofessional',
 'experienceresearch',
 'intern',
 'jul',
 '2022',
 'presentjammu',
 'indiadeveloped',
 'implemented',
 'sentiment',
 'analysis',
 'model',
 'extract',
 'classifyemotional',
 'context',
 'scraped',
 'reddit',
 'data',
 'suicidal',
 'discussions.utilized',
 'advanced',
 'technique',
 'including',
 'unsupervised',
 'pre-trained',
 'model',
 'e.g',
 'vader',
 'textblob',
 'clustering',
 'algorithm',
 'e.g',
 'kmeans',
 'dbscan',
 'accurately',
 'analyze',
 'andinterpret',
 'sentiment.enhanced',
 'model',
 'performance',
 'use',
 'deep',
 'learning',
 'technique',
 'aslstm',
 'bilstm',
 'etc',
 '\x00ne-tuning',
 'pre-trained',
 'word',
 'embeddings',
 'e.g',
 'glove',
 '.improved',
 'model',
 'accuracy',
 'applying',
 'different',
 'bert',
 'models.machine',
 'learning',
 'tarinee',
 'nov',
 '2020',
 'aug',
 '2021became',
 'pro\x00cient',
 'wide',
 'range',
 'machine',
 'learning',
 'algorithm',
 'including',
 'bangalore',
 'indiaunderlying',
 'mathematical',
 'principles.hands-on',
 'experience',
 'end-to-end',
 'machine',
 'learning',
 'project',
 'development',
 'dataacquisition',
 'model',
 'deployment.demonstrated',
 'expertise',
 'using',
 'cloud',
 'platform',
 'heroku',
 'streamlit',
 'aws',
 'ef\x00ciently',
 'deploy',
 'machine',
 'learning',
 'model',
 'solutions.rakshitraina1234',
 'gmail.com',
 '1',
 '2rakshit',
 'khajuriamachine',
 'learning',
 'engineertalab',
 'tillo',
 'gole',
 'gujral',
 '180002',
 'jammu',
 'india',
 'rakshitraina1234',
 'gmail.com',
 '914955615514',
 'aug',
 '2001',
 'http',
 '//www.linkedin.com/in/rakshit-khajuria-3627781b8/',
 'http',
 '//github.com/ryzxxl9149556155summaryskilled',
 'developing',
 'implementing',
 'data-driven',
 'solution',
 'real-world',
 'problem',
 'utilizing',
 'range',
 'tool',
 'andtechniques',
 'extract',
 'valuable',
 'insight',
 'large',
 'complex',
 'data',
 'set',
 'posse',
 'diverse',
 'experience',
 'cleaningand',
 'analyzing',
 'data',
 'enhancing',
 'existing',
 'model',
 'continuously',
 'seeking',
 'enhance',
 'skill',
 'broaden',
 'myknowledge',
 'dynamic',
 '\x00eld',
 'data',
 'science.skillstools',
 'python',
 'git',
 'github',
 'jupyter',
 'notebook',
 'anaconda',
 'v',
 'codepackages',
 'scikit-learn',
 'numpy',
 'panda',
 'matplotlib',
 'nltk',
 'tensorflow',
 'flask',
 'streamlit',
 'spacy',
 'text',
 'blob',
 'vader.machine',
 'learning',
 'supervised',
 'learning',
 'unsupervised',
 'learning',
 'clustering',
 'algorithm',
 'decision',
 'tree',
 'randomforests',
 'neural',
 'networks.nlp',
 'sentiment',
 'analysis',
 'text',
 'classi\x00cation',
 'named',
 'entity',
 'recognition',
 'word',
 'embedding',
 'topic',
 'modeling',
 'deeplearning',
 'nlp',
 'model',
 'e.g',
 '.',
 'transformer',
 'bert',
 'lstms',
 'soft',
 'skillstime',
 'management',
 'problem-solving',
 'leadership',
 'teamwork',
 'presentation',
 'skill',
 'con\x00denceprofessional',
 'experienceresearch',
 'intern',
 'jul',
 '2022',
 'presentjammu',
 'indiadeveloped',
 'implemented',
 'sentiment',
 'analysis',
 'model',
 'extract',
 'classifyemotional',
 'context',
 'scraped',
 'reddit',
 'data',
 'suicidal',
 'discussions.utilized',
 'advanced',
 'technique',
 'including',
 'unsupervised',
 'pre-trained',
 'model',
 'e.g',
 'vader',
 'textblob',
 'clustering',
 'algorithm',
 'e.g',
 'kmeans',
 'dbscan',
 'accurately',
 'analyze',
 'andinterpret',
 'sentiment.enhanced',
 'model',
 'performance',
 'use',
 'deep',
 'learning',
 'technique',
 'aslstm',
 'bilstm',
 'etc',
 '\x00ne-tuning',
 'pre-trained',
 'word',
 'embeddings',
 'e.g',
 'glove',
 '.improved',
 'model',
 'accuracy',
 'applying',
 'different',
 'bert',
 'models.machine',
 'learning',
 'tarinee',
 'nov',
 '2020',
 'aug',
 '2021became',
 'pro\x00cient',
 'wide',
 'range',
 'machine',
 'learning',
 'algorithm',
 'including',
 'bangalore',
 'indiaunderlying',
 'mathematical',
 'principles.hands-on',
 'experience',
 'end-to-end',
 'machine',
 'learning',
 'project',
 'development',
 'dataacquisition',
 'model',
 'deployment.demonstrated',
 'expertise',
 'using',
 'cloud',
 'platform',
 'heroku',
 'streamlit',
 'aws',
 'ef\x00ciently',
 'deploy',
 'machine',
 'learning',
 'model',
 'solutions.rakshitraina1234',
 'gmail.com',
 '1',
 '2projectsmulti',
 'purpose',
 'nlp',
 'application',
 'nlpify',
 'nov',
 '2022',
 'nov',
 '2022developed',
 'sophisticated',
 'ai',
 'platform',
 'extract',
 'various',
 'nlp',
 'feature',
 'includingsentiment',
 'analysis',
 'named',
 'entity',
 'recognition',
 'text',
 'summarization',
 'appreview',
 'data.performed',
 'extensive',
 'data',
 'preprocessing',
 'using',
 'technique',
 'tokenization',
 'lemmatization',
 'vectorization',
 'transform',
 'raw',
 'data',
 'machine-readableformat.createda',
 'multi-class',
 'classi\x00cation',
 'model',
 'using',
 'logistic',
 'regression',
 'textvectorization',
 'pipeline',
 'predict',
 'sentiment',
 'deployed',
 'platform',
 'user-friendly',
 'web',
 'app',
 'using',
 'streamlit',
 'framework.political',
 'spectrum',
 'detection',
 'medium',
 'news',
 'using',
 'deep-learning',
 'shap',
 'oct',
 '2022',
 'oct',
 '2022pythonbuilta',
 'political',
 'spectrum',
 'detection',
 'deep',
 'learning',
 'sequential',
 'model.performed',
 'nlp',
 'based',
 'tokenization',
 'lemmatization',
 'vectorization',
 'processed',
 'datausing',
 'neattext',
 'machine',
 'understandable',
 'language.simpli\x00ed',
 'code',
 'library',
 'shap',
 'built',
 'theoretic',
 'approach',
 'explain',
 'output',
 'ofsequential',
 'deep',
 'learning',
 'model.diabetes',
 'prediction',
 'using',
 'flask',
 'dec',
 '2021',
 'jan',
 '2022conducted',
 'in-depth',
 'data',
 'analysis',
 'national',
 'institute',
 'diabetes',
 'digestiveand',
 'kidney',
 'disease',
 'datasetbuilt',
 'multiple',
 'machine',
 'learning',
 'model',
 'including',
 'random',
 'forest',
 'logistic',
 'regression',
 'knn',
 'svm',
 'prediction',
 'various',
 'onset',
 'type',
 '2',
 'diabetescreated',
 'full-stack',
 'application',
 'using',
 'flask',
 'deployed',
 'heroku',
 'publicaccess',
 'http',
 '//diabetes-prediction-app02.herokuapp.com/certificatesibm',
 'data',
 'science',
 'specialization',
 'machine',
 'learning',
 'deep',
 'learning',
 'traineeineuron.aimathematics',
 'machine',
 'learningdata',
 'sciencestatistics',
 'foundation',
 'linkedinmachine',
 'learning',
 'pythoneducationelectronics',
 'communication',
 'engineering',
 'smvd',
 'university',
 'reasi',
 'j',
 'k',
 'jul',
 '2019',
 'jul',
 '2023jammu',
 'indiaorganisationsa.i',
 'circleactivelyparticipated',
 'a.i',
 'circle',
 'collaborating',
 'team',
 'member',
 'machine',
 'learning',
 'project',
 'mentoringjunior',
 'member',
 'machine',
 'learning',
 'potential',
 'applicationsinterestscoding',
 'football',
 'sketching',
 'machine',
 'learning',
 'deep',
 'learning',
 'mathematicsrakshitraina1234',
 'gmail.com',
 '2',
 '2']

In [137]:
key_word = get_key_word(NLP_Processed_CV)
key_word

(('\x00eld', 'data'), 2)
(('\x00ne-tuning', 'pre-trained'), 2)
(('.', 'transformer'), 2)
(('.improved', 'model'), 2)
(('//github.com/ryzxxl9149556155summaryskilled', 'developing'), 2)
(('//www.linkedin.com/in/rakshit-khajuria-3627781b8/', 'http'), 2)
(('180002', 'jammu'), 2)
(('2001', 'http'), 2)
(('2020', 'aug'), 2)
(('2021became', 'pro\x00cient'), 2)
(('2022', 'presentjammu'), 2)
(('914955615514', 'aug'), 2)
(('accuracy', 'applying'), 2)
(('accurately', 'analyze'), 2)
(('advanced', 'technique'), 2)
(('algorithm', 'decision'), 2)
(('algorithm', 'e.g'), 2)
(('algorithm', 'including'), 2)
(('anaconda', 'v'), 2)
(('analysis', 'model'), 2)
(('analysis', 'text'), 2)
(('analyze', 'andinterpret'), 2)
(('analyzing', 'data'), 2)
(('andinterpret', 'sentiment.enhanced'), 2)
(('andtechniques', 'extract'), 2)
(('applying', 'different'), 2)
(('aslstm', 'bilstm'), 2)
(('aug', '2001'), 2)
(('aug', '2021became'), 2)
(('aws', 'ef\x00ciently'), 2)
(('bangalore', 'indiaunderlying'), 2)
(('bert', 'lstms'), 2)
(('bert', 'models.machine'), 2)
(('bilstm', 'etc'), 2)
(('blob', 'vader.machine'), 2)
(('broaden', 'myknowledge'), 2)
(('classi\x00cation', 'named'), 2)
(('classifyemotional', 'context'), 2)
(('cleaningand', 'analyzing'), 2)
(('cloud', 'platform'), 2)
(('clustering', 'algorithm'), 4)
(('codepackages', 'scikit-learn'), 2)
(('complex', 'data'), 2)
(('con\x00denceprofessional', 'experienceresearch'), 2)
(('context', 'scraped'), 2)
(('continuously', 'seeking'), 2)
(('data', 'enhancing'), 2)
(('data', 'science.skillstools'), 2)
(('data', 'set'), 2)
(('data', 'suicidal'), 2)
(('data-driven', 'solution'), 2)
(('dataacquisition', 'model'), 2)
(('dbscan', 'accurately'), 2)
(('decision', 'tree'), 2)
(('deep', 'learning'), 6)
(('deeplearning', 'nlp'), 2)
(('deploy', 'machine'), 2)
(('deployment.demonstrated', 'expertise'), 2)
(('developing', 'implementing'), 2)
(('development', 'dataacquisition'), 2)
(('different', 'bert'), 2)
(('discussions.utilized', 'advanced'), 2)
(('diverse', 'experience'), 2)
(('dynamic', '\x00eld'), 2)
(('e.g', '.'), 2)
(('e.g', 'glove'), 2)
(('e.g', 'kmeans'), 2)
(('e.g', 'vader'), 2)
(('ef\x00ciently', 'deploy'), 2)
(('embedding', 'topic'), 2)
(('embeddings', 'e.g'), 2)
(('end-to-end', 'machine'), 2)
(('engineertalab', 'tillo'), 2)
(('enhance', 'skill'), 2)
(('enhancing', 'existing'), 2)
(('entity', 'recognition'), 3)
(('etc', '\x00ne-tuning'), 2)
(('existing', 'model'), 2)
(('experience', 'cleaningand'), 2)
(('experience', 'end-to-end'), 2)
(('experienceresearch', 'intern'), 2)
(('expertise', 'using'), 2)
(('extract', 'classifyemotional'), 2)
(('extract', 'valuable'), 2)
(('flask', 'streamlit'), 2)
(('git', 'github'), 2)
(('github', 'jupyter'), 2)
(('glove', '.improved'), 2)
(('gmail.com', '1'), 2)
(('gmail.com', '914955615514'), 2)
(('gole', 'gujral'), 2)
(('gujral', '180002'), 2)
(('heroku', 'streamlit'), 2)
(('http', '//github.com/ryzxxl9149556155summaryskilled'), 2)
(('http', '//www.linkedin.com/in/rakshit-khajuria-3627781b8/'), 2)
(('implemented', 'sentiment'), 2)
(('implementing', 'data-driven'), 2)
(('including', 'bangalore'), 2)
(('including', 'unsupervised'), 2)
(('india', 'rakshitraina1234'), 2)
(('indiadeveloped', 'implemented'), 2)
(('indiaunderlying', 'mathematical'), 2)
(('insight', 'large'), 2)
(('intern', 'jul'), 2)
(('jammu', 'india'), 2)
(('jul', '2022'), 2)
(('jupyter', 'notebook'), 2)
(('khajuriamachine', 'learning'), 2)
(('kmeans', 'dbscan'), 2)
(('large', 'complex'), 2)
(('leadership', 'teamwork'), 2)
(('learning', 'algorithm'), 2)
(('learning', 'clustering'), 2)
(('learning', 'deep'), 2)
(('learning', 'engineertalab'), 2)
(('learning', 'model'), 3)
(('learning', 'project'), 3)
(('learning', 'supervised'), 2)
(('learning', 'tarinee'), 2)
(('learning', 'technique'), 2)
(('learning', 'unsupervised'), 2)
(('lemmatization', 'vectorization'), 2)
(('logistic', 'regression'), 2)
(('lstms', 'soft'), 2)
(('machine', 'learning'), 11)
(('management', 'problem-solving'), 2)
(('mathematical', 'principles.hands-on'), 2)
(('matplotlib', 'nltk'), 2)
(('member', 'machine'), 2)
(('model', 'accuracy'), 2)
(('model', 'continuously'), 2)
(('model', 'deployment.demonstrated'), 2)
(('model', 'e.g'), 4)
(('model', 'extract'), 2)
(('model', 'performance'), 2)
(('model', 'solutions.rakshitraina1234'), 2)
(('modeling', 'deeplearning'), 2)
(('models.machine', 'learning'), 2)
(('myknowledge', 'dynamic'), 2)
(('named', 'entity'), 3)
(('networks.nlp', 'sentiment'), 2)
(('neural', 'networks.nlp'), 2)
(('nlp', 'model'), 2)
(('nltk', 'tensorflow'), 2)
(('notebook', 'anaconda'), 2)
(('nov', '2020'), 2)
(('numpy', 'panda'), 2)
(('panda', 'matplotlib'), 2)
(('performance', 'use'), 2)
(('platform', 'heroku'), 2)
(('posse', 'diverse'), 2)
(('pre-trained', 'model'), 2)
(('pre-trained', 'word'), 2)
(('presentation', 'skill'), 2)
(('presentjammu', 'indiadeveloped'), 2)
(('principles.hands-on', 'experience'), 2)
(('pro\x00cient', 'wide'), 2)
(('problem', 'utilizing'), 2)
(('problem-solving', 'leadership'), 2)
(('project', 'development'), 2)
(('python', 'git'), 2)
(('rakshitraina1234', 'gmail.com'), 2)
(('randomforests', 'neural'), 2)
(('range', 'machine'), 2)
(('range', 'tool'), 2)
(('real-world', 'problem'), 2)
(('recognition', 'word'), 2)
(('reddit', 'data'), 2)
(('science.skillstools', 'python'), 2)
(('scikit-learn', 'numpy'), 2)
(('scraped', 'reddit'), 2)
(('seeking', 'enhance'), 2)
(('sentiment', 'analysis'), 4)
(('sentiment.enhanced', 'model'), 2)
(('set', 'posse'), 2)
(('skill', 'broaden'), 2)
(('skill', 'con\x00denceprofessional'), 2)
(('skillstime', 'management'), 2)
(('soft', 'skillstime'), 2)
(('solution', 'real-world'), 2)
(('solutions.rakshitraina1234', 'gmail.com'), 2)
(('spacy', 'text'), 2)
(('spectrum', 'detection'), 2)
(('streamlit', 'aws'), 2)
(('streamlit', 'spacy'), 2)
(('suicidal', 'discussions.utilized'), 2)
(('supervised', 'learning'), 2)
(('tarinee', 'nov'), 2)
(('teamwork', 'presentation'), 2)
(('technique', 'aslstm'), 2)
(('technique', 'including'), 2)
(('tensorflow', 'flask'), 2)
(('text', 'blob'), 2)
(('text', 'classi\x00cation'), 2)
(('textblob', 'clustering'), 2)
(('tillo', 'gole'), 2)
(('tokenization', 'lemmatization'), 2)
(('tool', 'andtechniques'), 2)
(('topic', 'modeling'), 2)
(('transformer', 'bert'), 2)
(('tree', 'randomforests'), 2)
(('unsupervised', 'learning'), 2)
(('unsupervised', 'pre-trained'), 2)
(('use', 'deep'), 2)
(('using', 'cloud'), 2)
(('using', 'flask'), 2)
(('utilizing', 'range'), 2)
(('v', 'codepackages'), 2)
(('vader', 'textblob'), 2)
(('vader.machine', 'learning'), 2)
(('valuable', 'insight'), 2)
(('wide', 'range'), 2)
(('word', 'embedding'), 2)
(('word', 'embeddings'), 2)

['\x00eld data',
 '\x00ne-tuning pre-trained',
 '. transformer',
 '.improved model',
 '//github.com/ryzxxl9149556155summaryskilled developing',
 '//www.linkedin.com/in/rakshit-khajuria-3627781b8/ http',
 '180002 jammu',
 '2001 http',
 '2020 aug',
 '2021became pro\x00cient',
 '2022 presentjammu',
 '914955615514 aug',
 'accuracy applying',
 'accurately analyze',
 'advanced technique',
 'algorithm decision',
 'algorithm e.g',
 'algorithm including',
 'anaconda v',
 'analysis model',
 'analysis text',
 'analyze andinterpret',
 'analyzing data',
 'andinterpret sentiment.enhanced',
 'andtechniques extract',
 'applying different',
 'aslstm bilstm',
 'aug 2001',
 'aug 2021became',
 'aws ef\x00ciently',
 'bangalore indiaunderlying',
 'bert lstms',
 'bert models.machine',
 'bilstm etc',
 'blob vader.machine',
 'broaden myknowledge',
 'classi\x00cation named',
 'classifyemotional context',
 'cleaningand analyzing',
 'cloud platform',
 'clustering algorithm',
 'codepackages scikit-learn',
 'complex data',
 'con\x00denceprofessional experienceresearch',
 'context scraped',
 'continuously seeking',
 'data enhancing',
 'data science.skillstools',
 'data set',
 'data suicidal',
 'data-driven solution',
 'dataacquisition model',
 'dbscan accurately',
 'decision tree',
 'deep learning',
 'deeplearning nlp',
 'deploy machine',
 'deployment.demonstrated expertise',
 'developing implementing',
 'development dataacquisition',
 'different bert',
 'discussions.utilized advanced',
 'diverse experience',
 'dynamic \x00eld',
 'e.g .',
 'e.g glove',
 'e.g kmeans',
 'e.g vader',
 'ef\x00ciently deploy',
 'embedding topic',
 'embeddings e.g',
 'end-to-end machine',
 'engineertalab tillo',
 'enhance skill',
 'enhancing existing',
 'entity recognition',
 'etc \x00ne-tuning',
 'existing model',
 'experience cleaningand',
 'experience end-to-end',
 'experienceresearch intern',
 'expertise using',
 'extract classifyemotional',
 'extract valuable',
 'flask streamlit',
 'git github',
 'github jupyter',
 'glove .improved',
 'gmail.com 1',
 'gmail.com 914955615514',
 'gole gujral',
 'gujral 180002',
 'heroku streamlit',
 'http //github.com/ryzxxl9149556155summaryskilled',
 'http //www.linkedin.com/in/rakshit-khajuria-3627781b8/',
 'implemented sentiment',
 'implementing data-driven',
 'including bangalore',
 'including unsupervised',
 'india rakshitraina1234',
 'indiadeveloped implemented',
 'indiaunderlying mathematical',
 'insight large',
 'intern jul',
 'jammu india',
 'jul 2022',
 'jupyter notebook',
 'khajuriamachine learning',
 'kmeans dbscan',
 'large complex',
 'leadership teamwork',
 'learning algorithm',
 'learning clustering',
 'learning deep',
 'learning engineertalab',
 'learning model',
 'learning project',
 'learning supervised',
 'learning tarinee',
 'learning technique',
 'learning unsupervised',
 'lemmatization vectorization',
 'logistic regression',
 'lstms soft',
 'machine learning',
 'management problem-solving',
 'mathematical principles.hands-on',
 'matplotlib nltk',
 'member machine',
 'model accuracy',
 'model continuously',
 'model deployment.demonstrated',
 'model e.g',
 'model extract',
 'model performance',
 'model solutions.rakshitraina1234',
 'modeling deeplearning',
 'models.machine learning',
 'myknowledge dynamic',
 'named entity',
 'networks.nlp sentiment',
 'neural networks.nlp',
 'nlp model',
 'nltk tensorflow',
 'notebook anaconda',
 'nov 2020',
 'numpy panda',
 'panda matplotlib',
 'performance use',
 'platform heroku',
 'posse diverse',
 'pre-trained model',
 'pre-trained word',
 'presentation skill',
 'presentjammu indiadeveloped',
 'principles.hands-on experience',
 'pro\x00cient wide',
 'problem utilizing',
 'problem-solving leadership',
 'project development',
 'python git',
 'rakshitraina1234 gmail.com',
 'randomforests neural',
 'range machine',
 'range tool',
 'real-world problem',
 'recognition word',
 'reddit data',
 'science.skillstools python',
 'scikit-learn numpy',
 'scraped reddit',
 'seeking enhance',
 'sentiment analysis',
 'sentiment.enhanced model',
 'set posse',
 'skill broaden',
 'skill con\x00denceprofessional',
 'skillstime management',
 'soft skillstime',
 'solution real-world',
 'solutions.rakshitraina1234 gmail.com',
 'spacy text',
 'spectrum detection',
 'streamlit aws',
 'streamlit spacy',
 'suicidal discussions.utilized',
 'supervised learning',
 'tarinee nov',
 'teamwork presentation',
 'technique aslstm',
 'technique including',
 'tensorflow flask',
 'text blob',
 'text classi\x00cation',
 'textblob clustering',
 'tillo gole',
 'tokenization lemmatization',
 'tool andtechniques',
 'topic modeling',
 'transformer bert',
 'tree randomforests',
 'unsupervised learning',
 'unsupervised pre-trained',
 'use deep',
 'using cloud',
 'using flask',
 'utilizing range',
 'v codepackages',
 'vader textblob',
 'vader.machine learning',
 'valuable insight',
 'wide range',
 'word embedding',
 'word embeddings']

# Importing scapped df

In [138]:
DF_PATH = "data.csv"

In [139]:
df = pd.read_csv(DF_PATH)
df

,id,company,positionName,description,salary,location,rating,reviewsCount,postedAt,externalApplyLink,url
0,2567a216d4af7021,AT&T,"SPECIALIST, DATA ANALYTICS",\n \n Experienced data analyst position that ...,NaN,"Hyderabad, Telangana",3.7,43942.0,Today,https://in.indeed.com/applystart?jk=2567a216d4...,https://www.indeed.co.in/rc/clk?jk=2567a216d4a...
1,442ad7cc38a6f7b8,ICICI Prudential Life,Data scientist,Roles and responsibilities:\n 1. Data processi...,NaN,"Mumbai, Maharashtra",4.0,1391.0,Just posted,https://in.indeed.com/applystart?jk=442ad7cc38...,https://www.indeed.co.in/rc/clk?jk=442ad7cc38a...
2,e0fe53f38f84e7bd,ICICI Prudential Life,Data scientist - Lead,Roles and responsibilities:\n 1. Data processi...,NaN,"Mumbai, Maharashtra",4.0,1391.0,Just posted,https://in.indeed.com/applystart?jk=e0fe53f38f...,https://www.indeed.co.in/rc/clk?jk=e0fe53f38f8...
3,363b96425a82d12d,TMI Group IN,Bot NLP Analyst,\n Job Information \n \n \n \n \n Salary...,"₹10,00,000 - ₹16,00,000 a year","Hyderabad, Telangana",NaN,NaN,1 day ago,https://in.indeed.com/applystart?jk=363b96425a...,https://www.indeed.co.in/rc/clk?jk=363b96425a8...
4,215ece39050fb3f5,Shairu Gems Diamonds PVT.LTD.,Senior Data Scientist,"Sr. Data Analyst,\nShairu Gems Diamonds PVT. L...","₹25,000 - ₹35,000 a month","Surat, Gujarat",NaN,NaN,Today,NaN,https://www.indeed.co.in/company/Shairu-Gems-D...
...,...,...,...,...,...,...,...,...,...,...,...
5497,f53ad1277acdc74c,VISION ESTEEM,Executive HR Admin,Urgently looking Executive HR and Admin for le...,"₹20,000 - ₹25,000 a month","Chandigarh, Chandigarh",NaN,NaN,2 days ago,NaN,https://www.indeed.co.in/company/vision-esteem...
5498,2b1b759b9c3a9246,L.R. Patel & Co,HR Recruiter,JOB OVERVIEW: The HR Assistant duties involve ...,"₹15,000 - ₹20,000 a month","Ahmedabad, Gujarat",NaN,NaN,2 days ago,NaN,https://www.indeed.co.in/company/L.R.-Patel-&-...
5499,745a1ac63a001f46,Proactive Consultants & Services,HR Recruiter,"Dear candidates,\nWe have an urgent Opening fo...","₹20,000 - ₹25,000 a month","New Delhi, Delhi",NaN,NaN,2 days ago,NaN,https://www.indeed.co.in/company/Proactive-Con...
5500,d7901b874316b5d7,American Academy of Financial Management India,Recruitment Executive,Roles & Responsibilities :\nDesign and update ...,"₹20,000 - ₹25,000 a month","Delhi, Delhi",NaN,NaN,2 days ago,NaN,https://www.indeed.co.in/company/American-Acad...
5501,837f8b5ef252bcd0,SV Placement Solutions,HR Recruiter (females only),\n Partnering with hiring managers to determin...,"₹8,000 - ₹12,000 a month","Patiala, Punjab",5.0,2.0,2 days ago,NaN,https://www.indeed.co.in/company/SV-Placement-...

In [140]:
df.shape

(5502, 11)

In [141]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5502 entries, 0 to 5501
Data columns (total 11 columns):
id                   5502 non-null object
company              5408 non-null object
positionName         5502 non-null object
description          5502 non-null object
salary               1248 non-null object
location             5502 non-null object
rating               3128 non-null float64
reviewsCount         3128 non-null float64
postedAt             5502 non-null object
externalApplyLink    4044 non-null object
url                  5502 non-null object
dtypes: float64(2), object(9)
memory usage: 473.0+ KB

In [142]:
df['All'] = df[df.columns[0:]].apply(
    lambda x: ','.join(x.dropna().astype(str)),
    axis=1
)

In [143]:
df

,id,company,positionName,description,salary,location,rating,reviewsCount,postedAt,externalApplyLink,url,All
0,2567a216d4af7021,AT&T,"SPECIALIST, DATA ANALYTICS",\n \n Experienced data analyst position that ...,NaN,"Hyderabad, Telangana",3.7,43942.0,Today,https://in.indeed.com/applystart?jk=2567a216d4...,https://www.indeed.co.in/rc/clk?jk=2567a216d4a...,"2567a216d4af7021,AT&T,SPECIALIST, DATA ANALYTI..."
1,442ad7cc38a6f7b8,ICICI Prudential Life,Data scientist,Roles and responsibilities:\n 1. Data processi...,NaN,"Mumbai, Maharashtra",4.0,1391.0,Just posted,https://in.indeed.com/applystart?jk=442ad7cc38...,https://www.indeed.co.in/rc/clk?jk=442ad7cc38a...,"442ad7cc38a6f7b8,ICICI Prudential Life,Data sc..."
2,e0fe53f38f84e7bd,ICICI Prudential Life,Data scientist - Lead,Roles and responsibilities:\n 1. Data processi...,NaN,"Mumbai, Maharashtra",4.0,1391.0,Just posted,https://in.indeed.com/applystart?jk=e0fe53f38f...,https://www.indeed.co.in/rc/clk?jk=e0fe53f38f8...,"e0fe53f38f84e7bd,ICICI Prudential Life,Data sc..."
3,363b96425a82d12d,TMI Group IN,Bot NLP Analyst,\n Job Information \n \n \n \n \n Salary...,"₹10,00,000 - ₹16,00,000 a year","Hyderabad, Telangana",NaN,NaN,1 day ago,https://in.indeed.com/applystart?jk=363b96425a...,https://www.indeed.co.in/rc/clk?jk=363b96425a8...,"363b96425a82d12d,TMI Group IN,Bot NLP Analyst,..."
4,215ece39050fb3f5,Shairu Gems Diamonds PVT.LTD.,Senior Data Scientist,"Sr. Data Analyst,\nShairu Gems Diamonds PVT. L...","₹25,000 - ₹35,000 a month","Surat, Gujarat",NaN,NaN,Today,NaN,https://www.indeed.co.in/company/Shairu-Gems-D...,"215ece39050fb3f5,Shairu Gems Diamonds PVT.LTD...."
...,...,...,...,...,...,...,...,...,...,...,...,...
5497,f53ad1277acdc74c,VISION ESTEEM,Executive HR Admin,Urgently looking Executive HR and Admin for le...,"₹20,000 - ₹25,000 a month","Chandigarh, Chandigarh",NaN,NaN,2 days ago,NaN,https://www.indeed.co.in/company/vision-esteem...,"f53ad1277acdc74c,VISION ESTEEM,Executive HR Ad..."
5498,2b1b759b9c3a9246,L.R. Patel & Co,HR Recruiter,JOB OVERVIEW: The HR Assistant duties involve ...,"₹15,000 - ₹20,000 a month","Ahmedabad, Gujarat",NaN,NaN,2 days ago,NaN,https://www.indeed.co.in/company/L.R.-Patel-&-...,"2b1b759b9c3a9246,L.R. Patel & Co,HR Recruiter,..."
5499,745a1ac63a001f46,Proactive Consultants & Services,HR Recruiter,"Dear candidates,\nWe have an urgent Opening fo...","₹20,000 - ₹25,000 a month","New Delhi, Delhi",NaN,NaN,2 days ago,NaN,https://www.indeed.co.in/company/Proactive-Con...,"745a1ac63a001f46,Proactive Consultants & Servi..."
5500,d7901b874316b5d7,American Academy of Financial Management India,Recruitment Executive,Roles & Responsibilities :\nDesign and update ...,"₹20,000 - ₹25,000 a month","Delhi, Delhi",NaN,NaN,2 days ago,NaN,https://www.indeed.co.in/company/American-Acad...,"d7901b874316b5d7,American Academy of Financial..."
5501,837f8b5ef252bcd0,SV Placement Solutions,HR Recruiter (females only),\n Partnering with hiring managers to determin...,"₹8,000 - ₹12,000 a month","Patiala, Punjab",5.0,2.0,2 days ago,NaN,https://www.indeed.co.in/company/SV-Placement-...,"837f8b5ef252bcd0,SV Placement Solutions,HR Rec..."

In [144]:
df['All']

0       2567a216d4af7021,AT&T,SPECIALIST, DATA ANALYTI...
1       442ad7cc38a6f7b8,ICICI Prudential Life,Data sc...
2       e0fe53f38f84e7bd,ICICI Prudential Life,Data sc...
3       363b96425a82d12d,TMI Group IN,Bot NLP Analyst,...
4       215ece39050fb3f5,Shairu Gems Diamonds PVT.LTD....
                              ...
5497    f53ad1277acdc74c,VISION ESTEEM,Executive HR Ad...
5498    2b1b759b9c3a9246,L.R. Patel & Co,HR Recruiter,...
5499    745a1ac63a001f46,Proactive Consultants & Servi...
5500    d7901b874316b5d7,American Academy of Financial...
5501    837f8b5ef252bcd0,SV Placement Solutions,HR Rec...
Name: All, Length: 5502, dtype: object

In [145]:
df["description"].replace(r'\n','', regex=True,inplace=True)
df["description"].replace(r'\r','', regex=True,inplace=True)  
df = df.replace(' ', '')
df.description = df.description.str.strip()
df.All = df.All.str.strip()

In [146]:
df

,id,company,positionName,description,salary,location,rating,reviewsCount,postedAt,externalApplyLink,url,All
0,2567a216d4af7021,AT&T,"SPECIALIST, DATA ANALYTICS",Experienced data analyst position that uses te...,NaN,"Hyderabad, Telangana",3.7,43942.0,Today,https://in.indeed.com/applystart?jk=2567a216d4...,https://www.indeed.co.in/rc/clk?jk=2567a216d4a...,"2567a216d4af7021,AT&T,SPECIALIST, DATA ANALYTI..."
1,442ad7cc38a6f7b8,ICICI Prudential Life,Data scientist,Roles and responsibilities: 1. Data processing...,NaN,"Mumbai, Maharashtra",4.0,1391.0,Just posted,https://in.indeed.com/applystart?jk=442ad7cc38...,https://www.indeed.co.in/rc/clk?jk=442ad7cc38a...,"442ad7cc38a6f7b8,ICICI Prudential Life,Data sc..."
2,e0fe53f38f84e7bd,ICICI Prudential Life,Data scientist - Lead,Roles and responsibilities: 1. Data processing...,NaN,"Mumbai, Maharashtra",4.0,1391.0,Just posted,https://in.indeed.com/applystart?jk=e0fe53f38f...,https://www.indeed.co.in/rc/clk?jk=e0fe53f38f8...,"e0fe53f38f84e7bd,ICICI Prudential Life,Data sc..."
3,363b96425a82d12d,TMI Group IN,Bot NLP Analyst,Job Information Salary ₹ 100000...,"₹10,00,000 - ₹16,00,000 a year","Hyderabad, Telangana",NaN,NaN,1 day ago,https://in.indeed.com/applystart?jk=363b96425a...,https://www.indeed.co.in/rc/clk?jk=363b96425a8...,"363b96425a82d12d,TMI Group IN,Bot NLP Analyst,..."
4,215ece39050fb3f5,Shairu Gems Diamonds PVT.LTD.,Senior Data Scientist,"Sr. Data Analyst,Shairu Gems Diamonds PVT. LTD...","₹25,000 - ₹35,000 a month","Surat, Gujarat",NaN,NaN,Today,NaN,https://www.indeed.co.in/company/Shairu-Gems-D...,"215ece39050fb3f5,Shairu Gems Diamonds PVT.LTD...."
...,...,...,...,...,...,...,...,...,...,...,...,...
5497,f53ad1277acdc74c,VISION ESTEEM,Executive HR Admin,Urgently looking Executive HR and Admin for le...,"₹20,000 - ₹25,000 a month","Chandigarh, Chandigarh",NaN,NaN,2 days ago,NaN,https://www.indeed.co.in/company/vision-esteem...,"f53ad1277acdc74c,VISION ESTEEM,Executive HR Ad..."
5498,2b1b759b9c3a9246,L.R. Patel & Co,HR Recruiter,JOB OVERVIEW: The HR Assistant duties involve ...,"₹15,000 - ₹20,000 a month","Ahmedabad, Gujarat",NaN,NaN,2 days ago,NaN,https://www.indeed.co.in/company/L.R.-Patel-&-...,"2b1b759b9c3a9246,L.R. Patel & Co,HR Recruiter,..."
5499,745a1ac63a001f46,Proactive Consultants & Services,HR Recruiter,"Dear candidates,We have an urgent Opening for ...","₹20,000 - ₹25,000 a month","New Delhi, Delhi",NaN,NaN,2 days ago,NaN,https://www.indeed.co.in/company/Proactive-Con...,"745a1ac63a001f46,Proactive Consultants & Servi..."
5500,d7901b874316b5d7,American Academy of Financial Management India,Recruitment Executive,Roles & Responsibilities :Design and update jo...,"₹20,000 - ₹25,000 a month","Delhi, Delhi",NaN,NaN,2 days ago,NaN,https://www.indeed.co.in/company/American-Acad...,"d7901b874316b5d7,American Academy of Financial..."
5501,837f8b5ef252bcd0,SV Placement Solutions,HR Recruiter (females only),Partnering with hiring managers to determine s...,"₹8,000 - ₹12,000 a month","Patiala, Punjab",5.0,2.0,2 days ago,NaN,https://www.indeed.co.in/company/SV-Placement-...,"837f8b5ef252bcd0,SV Placement Solutions,HR Rec..."

# Put keywords of the CV into a dataframe

In [147]:
df2 = pd.DataFrame()
# append columns to an empty DataFrame
df2['title'] = ["I"]
df2['job highlights'] = ["I"]
df2['job description'] = ["I"]
df2['company overview'] = ["I"]
df2['industry'] = ["I"]

# Compare with the key words from CV only
df2['All'] = " ".join(key_word)

In [148]:
df2

,title,job highlights,job description,company overview,industry,All
0,I,I,I,I,I, eld data  ne-tuning pre-trained . transformer...

In [149]:
df.columns

Index(['id', 'company', 'positionName', 'description', 'salary', 'location',
       'rating', 'reviewsCount', 'postedAt', 'externalApplyLink', 'url',
       'All'],
      dtype='object')

# Recomendation Function

#klnsdsd

In [150]:
def get_recommendation(top, df_all, scores):
    recommendation = pd.DataFrame(columns = ['positionName', 'company',"location",'id','description','score'])
    count = 0
    for i in top:
#         recommendation.at[count, 'ApplicantID'] = u
        
        recommendation.at[count, 'positionName'] = df['positionName'][i]
        recommendation.at[count, 'company'] = df['company'][i]
        recommendation.at[count, 'location'] = df['location'][i]
    
        recommendation.at[count, 'id'] = df.index[i]
        recommendation.at[count, 'description'] = df['description'][i]
        recommendation.at[count, 'score'] =  scores[count]
        count += 1
    return recommendation

## cosine_similarity + TfidfVectorizer function

In [151]:
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer


def TFIDF(scraped_data, cv):
    tfidf_vectorizer = TfidfVectorizer(stop_words='english')

    # TF-IDF Scraped data
    tfidf_jobid = tfidf_vectorizer.fit_transform(scraped_data)

    # TF-IDF CV
    user_tfidf = tfidf_vectorizer.transform(cv)

    # Using cosine_similarity on (Scraped data) & (CV)
    cos_similarity_tfidf = map(lambda x: cosine_similarity(user_tfidf,x),tfidf_jobid)

    output2 = list(cos_similarity_tfidf)
    return output2
    
output2 = TFIDF(df['All'], df2['All'])

In [152]:
len(output2)

5502

In [153]:
output2

[array([[0.0948479]]),
 array([[0.08444755]]),
 array([[0.08286146]]),
 array([[0.05021908]]),
 array([[0.02366749]]),
 array([[0.15034555]]),
 array([[0.14022676]]),
 array([[0.07491787]]),
 array([[0.0993632]]),
 array([[0.14995204]]),
 array([[0.1261072]]),
 array([[0.08431034]]),
 array([[0.10165101]]),
 array([[0.09643986]]),
 array([[0.00853993]]),
 array([[0.05932155]]),
 array([[0.0759698]]),
 array([[0.12229772]]),
 array([[0.06333626]]),
 array([[0.00534088]]),
 array([[0.0573566]]),
 array([[0.0707458]]),
 array([[0.03797819]]),
 array([[0.05862494]]),
 array([[0.05503736]]),
 array([[0.05776527]]),
 array([[0.12463742]]),
 array([[0.09500873]]),
 array([[0.14035184]]),
 array([[0.10671014]]),
 array([[0.02925474]]),
 array([[0.07469959]]),
 array([[0.08506797]]),
 array([[0.14452088]]),
 array([[0.08549496]]),
 array([[0.0236746]]),
 array([[0.07412399]]),
 array([[0.0093484]]),
 array([[0.04216777]]),
 array([[0.10975605]]),
 array([[0.0491647]]),
 array([[0.08877254]]),
 array([[0.09023626]]),
 array([[0.06165977]]),
 array([[0.08696396]]),
 array([[0.1271485]]),
 array([[0.11545093]]),
 array([[0.1321922]]),
 array([[0.01647288]]),
 array([[0.06417242]]),
 array([[0.03763149]]),
 array([[0.05617946]]),
 array([[0.11949512]]),
 array([[0.08295677]]),
 array([[0.18934018]]),
 array([[0.04005962]]),
 array([[0.07689397]]),
 array([[0.1036527]]),
 array([[0.07693671]]),
 array([[0.0575969]]),
 array([[0.06112937]]),
 array([[0.05687247]]),
 array([[0.08439527]]),
 array([[0.13012462]]),
 array([[0.06177299]]),
 array([[0.04592165]]),
 array([[0.13686995]]),
 array([[0.07102641]]),
 array([[0.07845583]]),
 array([[0.11259408]]),
 array([[0.10786041]]),
 array([[0.0350083]]),
 array([[0.02789605]]),
 array([[0.11736778]]),
 array([[0.16899126]]),
 array([[0.04802549]]),
 array([[0.059177]]),
 array([[0.05088643]]),
 array([[0.14154555]]),
 array([[0.0861187]]),
 array([[0.12821816]]),
 array([[0.0658273]]),
 array([[0.06825407]]),
 array([[0.07799178]]),
 array([[0.07466067]]),
 array([[0.02297001]]),
 array([[0.08876833]]),
 array([[0.07585015]]),
 array([[0.08126695]]),
 array([[0.02718643]]),
 array([[0.03510554]]),
 array([[0.2183736]]),
 array([[0.10045067]]),
 array([[0.07998307]]),
 array([[0.10124734]]),
 array([[0.21634486]]),
 array([[0.04824546]]),
 array([[0.14677648]]),
 array([[0.04252858]]),
 array([[0.03175235]]),
 array([[0.06620067]]),
 array([[0.06915717]]),
 array([[0.01597977]]),
 array([[0.03959834]]),
 array([[0.06415932]]),
 array([[0.07514436]]),
 array([[0.03380517]]),
 array([[0.0374693]]),
 array([[0.12390937]]),
 array([[0.09077645]]),
 array([[0.01032107]]),
 array([[0.09240642]]),
 array([[0.09818171]]),
 array([[0.08429702]]),
 array([[0.11781317]]),
 array([[0.12565713]]),
 array([[0.04007211]]),
 array([[0.05589257]]),
 array([[0.14104483]]),
 array([[0.03898832]]),
 array([[0.03870647]]),
 array([[0.0678437]]),
 array([[0.04686584]]),
 array([[0.02773406]]),
 array([[0.10546929]]),
 array([[0.03038143]]),
 array([[0.02292012]]),
 array([[0.077576]]),
 array([[0.06230739]]),
 array([[0.09297556]]),
 array([[0.03434624]]),
 array([[0.04823843]]),
 array([[0.01862305]]),
 array([[0.0469619]]),
 array([[0.06582292]]),
 array([[0.09924004]]),
 array([[0.07730551]]),
 array([[0.12489256]]),
 array([[0.07531748]]),
 array([[0.01258779]]),
 array([[0.15109675]]),
 array([[0.10824052]]),
 array([[0.105952]]),
 array([[0.02430236]]),
 array([[0.09939136]]),
 array([[0.01596392]]),
 array([[0.1145446]]),
 array([[0.14682201]]),
 array([[0.19290649]]),
 array([[0.05760759]]),
 array([[0.07892838]]),
 array([[0.12551225]]),
 array([[0.08081799]]),
 array([[0.09296925]]),
 array([[0.09937451]]),
 array([[0.09516856]]),
 array([[0.0507342]]),
 array([[0.04764614]]),
 array([[0.05151546]]),
 array([[0.00661363]]),
 array([[0.05646076]]),
 array([[0.14785989]]),
 array([[0.07550171]]),
 array([[0.01672597]]),
 array([[0.16762742]]),
 array([[0.07477781]]),
 array([[0.04759865]]),
 array([[0.04001368]]),
 array([[0.08261019]]),
 array([[0.05784173]]),
 array([[0.12485605]]),
 array([[0.08252964]]),
 array([[0.08164041]]),
 array([[0.0401597]]),
 array([[0.04708549]]),
 array([[0.05833574]]),
 array([[0.08630738]]),
 array([[0.05510818]]),
 array([[0.02832161]]),
 array([[0.01286449]]),
 array([[0.07046597]]),
 array([[0.08393413]]),
 array([[0.04252414]]),
 array([[0.18399061]]),
 array([[0.0508719]]),
 array([[0.12205299]]),
 array([[0.06143576]]),
 array([[0.05235189]]),
 array([[0.10690004]]),
 array([[0.0611478]]),
 array([[0.10370508]]),
 array([[0.07861398]]),
 array([[0.0968249]]),
 array([[0.12627658]]),
 array([[0.04589118]]),
 array([[0.0570305]]),
 array([[0.10010563]]),
 array([[0.03008484]]),
 array([[0.02779072]]),
 array([[0.14213374]]),
 array([[0.0051603]]),
 array([[0.06661495]]),
 array([[0.10494418]]),
 array([[0.07010099]]),
 array([[0.03808532]]),
 array([[0.11324677]]),
 array([[0.06857128]]),
 array([[0.06543968]]),
 array([[0.01688762]]),
 array([[0.04151012]]),
 array([[0.06592633]]),
 array([[0.07965617]]),
 array([[0.0799842]]),
 array([[0.05426014]]),
 array([[0.07086855]]),
 array([[0.07059596]]),
 array([[0.05519709]]),
 array([[0.06043492]]),
 array([[0.02098567]]),
 array([[0.12783785]]),
 array([[0.07382188]]),
 array([[0.15686334]]),
 array([[0.07453266]]),
 array([[0.18741848]]),
 array([[0.03915552]]),
 array([[0.15018374]]),
 array([[0.0971778]]),
 array([[0.06743514]]),
 array([[0.06963125]]),
 array([[0.15415774]]),
 array([[0.03326608]]),
 array([[0.04101796]]),
 array([[0.12129978]]),
 array([[0.07330532]]),
 array([[0.06784281]]),
 array([[0.03980999]]),
 array([[0.16364124]]),
 array([[0.03640413]]),
 array([[0.05314708]]),
 array([[0.07774736]]),
 array([[0.04964793]]),
 array([[0.13941309]]),
 array([[0.09322549]]),
 array([[0.10728542]]),
 array([[0.09963557]]),
 array([[0.04681001]]),
 array([[0.04335671]]),
 array([[0.15071372]]),
 array([[0.06375192]]),
 array([[0.07515757]]),
 array([[0.12070371]]),
 array([[0.11295722]]),
 array([[0.07932946]]),
 array([[0.07832562]]),
 array([[0.04767146]]),
 array([[0.06334027]]),
 array([[0.10573017]]),
 array([[0.05172929]]),
 array([[0.07174961]]),
 array([[0.03617876]]),
 array([[0.10845653]]),
 array([[0.09456342]]),
 array([[0.10798663]]),
 array([[0.03680369]]),
 array([[0.0755052]]),
 array([[0.05783791]]),
 array([[0.04618289]]),
 array([[0.04437287]]),
 array([[0.0645725]]),
 array([[0.04818693]]),
 array([[0.01451042]]),
 array([[0.08978848]]),
 array([[0.04309664]]),
 array([[0.08623947]]),
 array([[0.04639656]]),
 array([[0.15524107]]),
 array([[0.03087612]]),
 array([[0.0401505]]),
 array([[0.06104028]]),
 array([[0.08740825]]),
 array([[0.01789544]]),
 array([[0.11426533]]),
 array([[0.04581144]]),
 array([[0.08447864]]),
 array([[0.14942788]]),
 array([[0.15576254]]),
 array([[0.09610242]]),
 array([[0.06673394]]),
 array([[0.07969609]]),
 array([[0.04775181]]),
 array([[0.12862875]]),
 array([[0.0698897]]),
 array([[0.1344599]]),
 array([[0.0490482]]),
 array([[0.14492795]]),
 array([[0.03080372]]),
 array([[0.14541317]]),
 array([[0.06854873]]),
 array([[0.04806246]]),
 array([[0.04906247]]),
 array([[0.14592403]]),
 array([[0.13468128]]),
 array([[0.08014389]]),
 array([[0.03629719]]),
 array([[0.06225292]]),
 array([[0.14589861]]),
 array([[0.13580339]]),
 array([[0.16054463]]),
 array([[0.072098]]),
 array([[0.15453088]]),
 array([[0.06993673]]),
 array([[0.07050613]]),
 array([[0.07447708]]),
 array([[0.14977424]]),
 array([[0.11808604]]),
 array([[0.13733434]]),
 array([[0.16346635]]),
 array([[0.06272732]]),
 array([[0.0509862]]),
 array([[0.10289231]]),
 array([[0.07607765]]),
 array([[0.01819601]]),
 array([[0.10014069]]),
 array([[0.0581543]]),
 array([[0.03088721]]),
 array([[0.05353692]]),
 array([[0.016392]]),
 array([[0.14856236]]),
 array([[0.1179509]]),
 array([[0.09175346]]),
 array([[0.0828954]]),
 array([[0.04112261]]),
 array([[0.05354308]]),
 array([[0.05992475]]),
 array([[0.17723572]]),
 array([[0.08619138]]),
 array([[0.03025665]]),
 array([[0.176724]]),
 array([[0.13496532]]),
 array([[0.12150742]]),
 array([[0.05406141]]),
 array([[0.10740591]]),
 array([[0.0646959]]),
 array([[0.0234832]]),
 array([[0.09170187]]),
 array([[0.01184364]]),
 array([[0.06322696]]),
 array([[0.05432237]]),
 array([[0.1170428]]),
 array([[0.06987188]]),
 array([[0.16100963]]),
 array([[0.04492645]]),
 array([[0.09650498]]),
 array([[0.07181911]]),
 array([[0.05890542]]),
 array([[0.1328156]]),
 array([[0.09007258]]),
 array([[0.06090635]]),
 array([[0.01912853]]),
 array([[0.0454585]]),
 array([[0.06180783]]),
 array([[0.05990629]]),
 array([[0.06255317]]),
 array([[0.11672296]]),
 array([[0.09524597]]),
 array([[0.09190565]]),
 array([[0.13709446]]),
 array([[0.04855817]]),
 array([[0.08320183]]),
 array([[0.06568263]]),
 array([[0.04971]]),
 array([[0.12641644]]),
 array([[0.06494563]]),
 array([[0.13711872]]),
 array([[0.10582153]]),
 array([[0.0626148]]),
 array([[0.10522193]]),
 array([[0.13128261]]),
 array([[0.10104245]]),
 array([[0.07931728]]),
 array([[0.04704196]]),
 array([[0.04094459]]),
 array([[0.20880065]]),
 array([[0.04882855]]),
 array([[0.06541226]]),
 array([[0.04133812]]),
 array([[0.14671614]]),
 array([[0.12365319]]),
 array([[0.02950182]]),
 array([[0.14885586]]),
 array([[0.14927493]]),
 array([[0.05652205]]),
 array([[0.06296662]]),
 array([[0.01609347]]),
 array([[0.05203887]]),
 array([[0.13253174]]),
 array([[0.07217929]]),
 array([[0.03852373]]),
 array([[0.0662223]]),
 array([[0.11057539]]),
 array([[0.19301372]]),
 array([[0.120588]]),
 array([[0.06080165]]),
 array([[0.11577692]]),
 array([[0.05451364]]),
 array([[0.00718773]]),
 array([[0.03734878]]),
 array([[0.06465874]]),
 array([[0.08151265]]),
 array([[0.06208036]]),
 array([[0.14913996]]),
 array([[0.10375389]]),
 array([[0.07348948]]),
 array([[0.10695293]]),
 array([[0.02940182]]),
 array([[0.04282876]]),
 array([[0.13309741]]),
 array([[0.01819686]]),
 array([[0.13357808]]),
 array([[0.06293956]]),
 array([[0.09877794]]),
 array([[0.02631458]]),
 array([[0.02372292]]),
 array([[0.0474833]]),
 array([[0.09543607]]),
 array([[0.05608032]]),
 array([[0.10002693]]),
 array([[0.07710473]]),
 array([[0.0107791]]),
 array([[0.02368486]]),
 array([[0.13583678]]),
 array([[0.06601466]]),
 array([[0.07874591]]),
 array([[0.10760166]]),
 array([[0.04204419]]),
 array([[0.10763723]]),
 array([[0.06857142]]),
 array([[0.03879022]]),
 array([[0.09013892]]),
 array([[0.09520315]]),
 array([[0.02413191]]),
 array([[0.03970165]]),
 array([[0.0136992]]),
 array([[0.0076959]]),
 array([[0.15389073]]),
 array([[0.07409348]]),
 array([[0.11932859]]),
 array([[0.05614424]]),
 array([[0.12201517]]),
 array([[0.04640492]]),
 array([[0.14723955]]),
 array([[0.01754735]]),
 array([[0.02374805]]),
 array([[0.07230696]]),
 array([[0.13381486]]),
 array([[0.03587197]]),
 array([[0.0403879]]),
 array([[0.17282769]]),
 array([[0.08833269]]),
 array([[0.0624122]]),
 array([[0.0099876]]),
 array([[0.06985167]]),
 array([[0.05335974]]),
 array([[0.15197559]]),
 array([[0.14082022]]),
 array([[0.06284534]]),
 array([[0.02372758]]),
 array([[0.07775707]]),
 array([[0.07321709]]),
 array([[0.0818842]]),
 array([[0.11359138]]),
 array([[0.07581518]]),
 array([[0.04612385]]),
 array([[0.17033386]]),
 array([[0.11073109]]),
 array([[0.02988145]]),
 array([[0.02413231]]),
 array([[0.03195169]]),
 array([[0.09544358]]),
 array([[0.15757195]]),
 array([[0.22735629]]),
 array([[0.05300162]]),
 array([[0.06764734]]),
 array([[0.16727395]]),
 array([[0.05919381]]),
 array([[0.06724305]]),
 array([[0.06679514]]),
 array([[0.0296877]]),
 array([[0.09640798]]),
 array([[0.10914143]]),
 array([[0.07386393]]),
 array([[0.1165324]]),
 array([[0.05997811]]),
 array([[0.0869829]]),
 array([[0.06076366]]),
 array([[0.0639589]]),
 array([[0.03881139]]),
 array([[0.07069746]]),
 array([[0.07543611]]),
 array([[0.09266289]]),
 array([[0.0677071]]),
 array([[0.02435293]]),
 array([[0.04903625]]),
 array([[0.05862494]]),
 array([[0.07076992]]),
 array([[0.14022676]]),
 array([[0.03774076]]),
 array([[0.07373086]]),
 array([[0.04503623]]),
 array([[0.05872887]]),
 array([[0.03250636]]),
 array([[0.04095062]]),
 array([[0.03717485]]),
 array([[0.04861623]]),
 array([[0.06585507]]),
 array([[0.05329836]]),
 array([[0.0403199]]),
 array([[0.04690031]]),
 array([[0.03578025]]),
 array([[0.0332511]]),
 array([[0.05721912]]),
 array([[0.03109097]]),
 array([[0.02779405]]),
 array([[0.07356672]]),
 array([[0.02455358]]),
 array([[0.03278807]]),
 array([[0.03362476]]),
 array([[0.05111764]]),
 array([[0.03803782]]),
 array([[0.03513769]]),
 array([[0.10975605]]),
 array([[0.16899126]]),
 array([[0.0759698]]),
 array([[0.09643986]]),
 array([[0.05353058]]),
 array([[0.03577442]]),
 array([[0.03640041]]),
 array([[0.04162423]]),
 array([[0.02787232]]),
 array([[0.02889229]]),
 array([[0.03416129]]),
 array([[0.16282566]]),
 array([[0.10671014]]),
 array([[0.08880031]]),
 array([[0.05145906]]),
 array([[0.08325655]]),
 array([[0.04005962]]),
 array([[0.14452088]]),
 array([[0.04127061]]),
 array([[0.03147914]]),
 array([[0.03243504]]),
 array([[0.0354865]]),
 array([[0.04837185]]),
 array([[0.0637188]]),
 array([[0.12461559]]),
 array([[0.02953151]]),
 array([[0.08548509]]),
 array([[0.07299961]]),
 array([[0.05791557]]),
 array([[0.1078297]]),
 array([[0.04671177]]),
 array([[0.04352788]]),
 array([[0.18934018]]),
 array([[0.03551505]]),
 array([[0.03837969]]),
 array([[0.03310237]]),
 array([[0.06675064]]),
 array([[0.03415626]]),
 array([[0.11949512]]),
 array([[0.03566464]]),
 array([[0.03508994]]),
 array([[0.08691535]]),
 array([[0.04201726]]),
 array([[0.04013096]]),
 array([[0.03070652]]),
 array([[0.03959423]]),
 array([[0.03951184]]),
 array([[0.03352447]]),
 array([[0.0379985]]),
 array([[0.05882799]]),
 array([[0.03107575]]),
 array([[0.10367559]]),
 array([[0.08876833]]),
 array([[0.06675272]]),
 array([[0.06181815]]),
 array([[0.03900459]]),
 array([[0.0296189]]),
 array([[0.03646791]]),
 array([[0.11250982]]),
 array([[0.06701741]]),
 array([[0.11752986]]),
 array([[0.03584521]]),
 array([[0.06098917]]),
 array([[0.03793467]]),
 array([[0.12821816]]),
 array([[0.03372044]]),
 array([[0.11526073]]),
 array([[0.05580617]]),
 array([[0.08980689]]),
 array([[0.08082008]]),
 array([[0.08122781]]),
 array([[0.03343202]]),
 array([[0.13981479]]),
 array([[0.08788319]]),
 array([[0.07466067]]),
 array([[0.12568656]]),
 array([[0.03779471]]),
 array([[0.02718643]]),
 array([[0.05034093]]),
 array([[0.04697591]]),
 array([[0.03520486]]),
 array([[0.02302936]]),
 array([[0.03986179]]),
 array([[0.06421061]]),
 array([[0.02992275]]),
 array([[0.03757099]]),
 array([[0.07173155]]),
 array([[0.03193732]]),
 array([[0.07585015]]),
 array([[0.02193361]]),
 array([[0.06449754]]),
 array([[0.02522294]]),
 array([[0.10045067]]),
 array([[0.10137918]]),
 array([[0.06979245]]),
 array([[0.04815529]]),
 array([[0.05966882]]),
 array([[0.13237117]]),
 array([[0.02602762]]),
 array([[0.04243126]]),
 array([[0.04140174]]),
 array([[0.1236044]]),
 array([[0.0453034]]),
 array([[0.02305406]]),
 array([[0.07610186]]),
 array([[0.0543053]]),
 array([[0.03630023]]),
 array([[0.03470637]]),
 array([[0.11781317]]),
 array([[0.05589257]]),
 array([[0.03502046]]),
 array([[0.03194115]]),
 array([[0.05119762]]),
 array([[0.03155223]]),
 array([[0.04751335]]),
 array([[0.03813158]]),
 array([[0.04111349]]),
 array([[0.02935952]]),
 array([[0.0752888]]),
 array([[0.03865339]]),
 array([[0.05188366]]),
 array([[0.04662722]]),
 array([[0.03885112]]),
 array([[0.04761032]]),
 array([[0.0684703]]),
 array([[0.09240642]]),
 array([[0.04595667]]),
 array([[0.02172777]]),
 array([[0.07514436]]),
 array([[0.12390937]]),
 array([[0.02492776]]),
 array([[0.06415932]]),
 array([[0.07021902]]),
 array([[0.11462424]]),
 array([[0.06575721]]),
 array([[0.06612749]]),
 array([[0.04707073]]),
 array([[0.02836315]]),
 array([[0.0697086]]),
 array([[0.02883034]]),
 array([[0.09728544]]),
 array([[0.06249061]]),
 array([[0.02828429]]),
 array([[0.077576]]),
 array([[0.03538614]]),
 array([[0.04695243]]),
 array([[0.03081345]]),
 array([[0.04825745]]),
 array([[0.09005207]]),
 array([[0.05809763]]),
 array([[0.06594947]]),
 array([[0.027319]]),
 array([[0.04192523]]),
 array([[0.07233107]]),
 array([[0.05932085]]),
 array([[0.12783785]]),
 array([[0.03291972]]),
 array([[0.14785989]]),
 array([[0.0499813]]),
 array([[0.07781032]]),
 array([[0.07550171]]),
 array([[0.03361325]]),
 array([[0.07164433]]),
 array([[0.06617298]]),
 array([[0.01811839]]),
 array([[0.09516856]]),
 array([[0.08773582]]),
 array([[0.04514779]]),
 array([[0.04633323]]),
 array([[0.06028973]]),
 array([[0.03740912]]),
 array([[0.03349468]]),
 array([[0.03932023]]),
 array([[0.05469449]]),
 array([[0.10617621]]),
 array([[0.03723819]]),
 array([[0.06366003]]),
 array([[0.06787086]]),
 array([[0.07184153]]),
 array([[0.08667379]]),
 array([[0.15018254]]),
 array([[0.16370938]]),
 array([[0.13941309]]),
 array([[0.15679728]]),
 array([[0.14213374]]),
 array([[0.04830711]]),
 array([[0.09937451]]),
 array([[0.03648883]]),
 array([[0.03116928]]),
 array([[0.03886689]]),
 array([[0.05625057]]),
 array([[0.16402229]]),
 array([[0.02561391]]),
 array([[0.06296574]]),
 array([[0.02089845]]),
 array([[0.03239878]]),
 array([[0.10370508]]),
 array([[0.10570514]]),
 array([[0.03553643]]),
 array([[0.03091748]]),
 array([[0.11299794]]),
 array([[0.18741848]]),
 array([[0.07892838]]),
 array([[0.02301585]]),
 array([[0.12551225]]),
 array([[0.03269521]]),
 array([[0.06338477]]),
 array([[0.070077]]),
 array([[0.1448827]]),
 array([[0.09869956]]),
 array([[0.14915174]]),
 array([[0.14541317]]),
 array([[0.06590736]]),
 array([[0.06661495]]),
 array([[0.06854873]]),
 array([[0.07861398]]),
 array([[0.19294038]]),
 array([[0.08081799]]),
 array([[0.06128083]]),
 array([[0.08252964]]),
 array([[0.06406252]]),
 array([[0.03860528]]),
 array([[0.15434615]]),
 array([[0.03443929]]),
 array([[0.0826439]]),
 array([[0.05270338]]),
 array([[0.02126102]]),
 array([[0.09336803]]),
 array([[0.09121228]]),
 array([[0.08975605]]),
 array([[0.02588283]]),
 array([[0.06319483]]),
 array([[0.04174624]]),
 array([[0.08630738]]),
 array([[0.07389706]]),
 array([[0.07049763]]),
 array([[0.0971778]]),
 array([[0.04784696]]),
 array([[0.02318504]]),
 array([[0.03425539]]),
 array([[0.02977357]]),
 array([[0.03582221]]),
 array([[0.09456342]]),
 array([[0.05508682]]),
 array([[0.06352474]]),
 array([[0.06393089]]),
 array([[0.05169572]]),
 array([[0.05129215]]),
 array([[0.07610055]]),
 array([[0.1964954]]),
 array([[0.03702483]]),
 array([[0.07382188]]),
 array([[0.08799747]]),
 array([[0.05642427]]),
 array([[0.04618289]]),
 array([[0.09380381]]),
 array([[0.02522946]]),
 array([[0.0991694]]),
 array([[0.03492731]]),
 array([[0.05397887]]),
 array([[0.05771348]]),
 array([[0.05236615]]),
 array([[0.06189672]]),
 array([[0.0442309]]),
 array([[0.08332309]]),
 array([[0.11426533]]),
 array([[0.04863696]]),
 array([[0.04065896]]),
 array([[0.03223948]]),
 array([[0.09607412]]),
 array([[0.03553059]]),
 array([[0.08256781]]),
 array([[0.03399344]]),
 array([[0.05159683]]),
 array([[0.11251546]]),
 array([[0.02572748]]),
 array([[0.07498646]]),
 array([[0.06039213]]),
 array([[0.03238922]]),
 array([[0.02628205]]),
 array([[0.12627658]]),
 array([[0.03353509]]),
 array([[0.0593578]]),
 array([[0.06252408]]),
 array([[0.04964793]]),
 array([[0.03342419]]),
 array([[0.05788518]]),
 array([[0.03516794]]),
 array([[0.03996171]]),
 array([[0.05675108]]),
 array([[0.04222707]]),
 array([[0.12066402]]),
 array([[0.05120447]]),
 array([[0.03602975]]),
 array([[0.05461596]]),
 array([[0.02464142]]),
 array([[0.03635826]]),
 array([[0.07298374]]),
 array([[0.09105174]]),
 array([[0.04876742]]),
 array([[0.05314708]]),
 array([[0.0699135]]),
 array([[0.04847418]]),
 array([[0.12062963]]),
 array([[0.04515121]]),
 array([[0.02538725]]),
 array([[0.03891959]]),

In [154]:
top = sorted(range(len(output2)), key=lambda i: output2[i], reverse=True)[:100]
list_scores = [output2[i][0][0] for i in top]
TF=get_recommendation(top,df, list_scores)
TF

,positionName,company,location,description,score,JobID
0,Machine Learning Lead Engineer,Wasoko,"Bengaluru, Karnataka",Summary We are looking for an experienced ML ...,0.227356,480.0
1,Data Scientist,Chubb INA Holdings Inc.,"Bengaluru, Karnataka",Job Requirements Responsibilities Work with b...,0.218374,91.0
2,Data Science - Knowledge Graph,Chubb INA Holdings Inc.,"Bengaluru, Karnataka",Work Experience Work with business partners gl...,0.216345,95.0
3,"Manager MLOps, Data Science",Mondelēz International,"Mumbai, Maharashtra",Job Description Are You Ready to Make It Hap...,0.208801,382.0
4,"Manager MLOps, Data Science",Mondelēz International,"Mumbai, Maharashtra",Job Description Are You Ready to Make It Hap...,0.208801,982.0
...,...,...,...,...,...,...
95,Deputy Manager-Aftermarket and Service (Data S...,Pratt & Whitney,"Bengaluru, Karnataka",Date Posted: +91-XXXXXXXXXX:00 Country: Indi...,0.13687,66.0
96,Data Science (NLP) Intern,Emplay Inc,Remote,"Job Title: NLP/Data Science InternStipend- 20,...",0.135837,430.0
97,Data Science and Business Analytics,Zotto Limited,"Delhi, Delhi",We are looking for a Data Scientist who will s...,0.135803,306.0
98,Lead Machine Learning Firmware Test Engineer,Axiado,"Hyderabad, Telangana",Company Description Axiado is an AI-enhanced ...,0.134965,338.0
99,Lead Machine Learning Firmware Test Engineer,Axiado,"Hyderabad, Telangana",Company Description Axiado is an AI-enhanced ...,0.134965,872.0

## cosine_similarity + CountVectorizer

In [155]:

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

count_vectorizer = CountVectorizer()
count_jobid = count_vectorizer.fit_transform(df['All']) #converting job data into vectors using count vectorizers
count_jobid

<5502x46684 sparse matrix of type '<class 'numpy.int64'>'
	with 1652794 stored elements in Compressed Sparse Row format>

In [156]:
# print(count_jobid)

In [157]:
user_count = count_vectorizer.transform(df2['All'])#converting user cv data into vectors using count vectorizers
user_count

<1x46684 sparse matrix of type '<class 'numpy.int64'>'
	with 153 stored elements in Compressed Sparse Row format>

In [158]:
print(user_count)

  (0, 2274)	2
  (0, 2325)	2
  (0, 2327)	2
  (0, 12586)	2
  (0, 12588)	2
  (0, 12913)	2
  (0, 13308)	5
  (0, 13530)	2
  (0, 13541)	3
  (0, 13564)	2
  (0, 13569)	2
  (0, 13633)	2
  (0, 13859)	2
  (0, 14410)	4
  (0, 14577)	2
  (0, 15198)	2
  (0, 15611)	4
  (0, 15905)	2
  (0, 19454)	2
  (0, 21367)	2
  (0, 21418)	3
  (0, 21648)	8
  (0, 21835)	2
  (0, 21915)	2
  (0, 22178)	2
  :	:
  (0, 42469)	4
  (0, 42728)	2
  (0, 43238)	2
  (0, 43274)	4
  (0, 43430)	2
  (0, 43508)	4
  (0, 43509)	2
  (0, 43860)	2
  (0, 43891)	1
  (0, 43920)	2
  (0, 43943)	2
  (0, 44067)	4
  (0, 44106)	2
  (0, 44186)	2
  (0, 44340)	2
  (0, 44775)	4
  (0, 44880)	2
  (0, 44898)	3
  (0, 44922)	2
  (0, 44924)	2
  (0, 45014)	2
  (0, 45919)	2
  (0, 46069)	4
  (0, 46139)	2
  (0, 46227)	2

In [159]:
cos_similarity_countv = map(lambda x: cosine_similarity(user_count, x),count_jobid)
output3 = list(cos_similarity_countv)
#output3

In [160]:
output3

[array([[0.18863457]]),
 array([[0.2481385]]),
 array([[0.24711524]]),
 array([[0.12716114]]),
 array([[0.12430384]]),
 array([[0.23386668]]),
 array([[0.20115459]]),
 array([[0.20418955]]),
 array([[0.15770306]]),
 array([[0.23541296]]),
 array([[0.25080731]]),
 array([[0.18570727]]),
 array([[0.18231442]]),
 array([[0.22774789]]),
 array([[0.05537236]]),
 array([[0.0799583]]),
 array([[0.17849324]]),
 array([[0.30074646]]),
 array([[0.1170298]]),
 array([[0.05451707]]),
 array([[0.13573859]]),
 array([[0.15172833]]),
 array([[0.08835674]]),
 array([[0.17444216]]),
 array([[0.13318677]]),
 array([[0.22569545]]),
 array([[0.1761057]]),
 array([[0.18522631]]),
 array([[0.21356688]]),
 array([[0.16262122]]),
 array([[0.07621885]]),
 array([[0.17871404]]),
 array([[0.20447945]]),
 array([[0.26653906]]),
 array([[0.15601432]]),
 array([[0.09008666]]),
 array([[0.14537883]]),
 array([[0.07635354]]),
 array([[0.12838091]]),
 array([[0.21095305]]),
 array([[0.12037814]]),
 array([[0.20474689]]),
 array([[0.22930282]]),
 array([[0.10448587]]),
 array([[0.20736408]]),
 array([[0.20396462]]),
 array([[0.18704908]]),
 array([[0.18728387]]),
 array([[0.08145212]]),
 array([[0.1324638]]),
 array([[0.09380183]]),
 array([[0.12592669]]),
 array([[0.27600695]]),
 array([[0.14561965]]),
 array([[0.28006901]]),
 array([[0.08265252]]),
 array([[0.13660632]]),
 array([[0.19523441]]),
 array([[0.18500072]]),
 array([[0.15907355]]),
 array([[0.10955626]]),
 array([[0.12261063]]),
 array([[0.18664412]]),
 array([[0.217115]]),
 array([[0.11616154]]),
 array([[0.11940869]]),
 array([[0.22629486]]),
 array([[0.13424123]]),
 array([[0.13348213]]),
 array([[0.27688397]]),
 array([[0.15934423]]),
 array([[0.16364469]]),
 array([[0.14307545]]),
 array([[0.29219337]]),
 array([[0.35609196]]),
 array([[0.14566764]]),
 array([[0.12898587]]),
 array([[0.20408118]]),
 array([[0.25702489]]),
 array([[0.21471876]]),
 array([[0.26461445]]),
 array([[0.17372721]]),
 array([[0.19338121]]),
 array([[0.21640362]]),
 array([[0.20044539]]),
 array([[0.07515174]]),
 array([[0.21225083]]),
 array([[0.2007994]]),
 array([[0.14316408]]),
 array([[0.078542]]),
 array([[0.13860009]]),
 array([[0.30461524]]),
 array([[0.19411555]]),
 array([[0.22936061]]),
 array([[0.16255885]]),
 array([[0.3024667]]),
 array([[0.17532602]]),
 array([[0.20831535]]),
 array([[0.12117065]]),
 array([[0.0895236]]),
 array([[0.17122726]]),
 array([[0.21088666]]),
 array([[0.08686174]]),
 array([[0.1703255]]),
 array([[0.10560213]]),
 array([[0.12652099]]),
 array([[0.11336959]]),
 array([[0.17218869]]),
 array([[0.26807622]]),
 array([[0.19026116]]),
 array([[0.04526346]]),
 array([[0.25324187]]),
 array([[0.211735]]),
 array([[0.17482307]]),
 array([[0.21204558]]),
 array([[0.17276779]]),
 array([[0.09768989]]),
 array([[0.13589468]]),
 array([[0.23049477]]),
 array([[0.13820129]]),
 array([[0.10935733]]),
 array([[0.16229404]]),
 array([[0.15644901]]),
 array([[0.10304599]]),
 array([[0.1440594]]),
 array([[0.08264046]]),
 array([[0.07719001]]),
 array([[0.09821246]]),
 array([[0.12158805]]),
 array([[0.18439617]]),
 array([[0.10757745]]),
 array([[0.1112204]]),
 array([[0.07092694]]),
 array([[0.11407695]]),
 array([[0.14401599]]),
 array([[0.1839176]]),
 array([[0.19411189]]),
 array([[0.2196549]]),
 array([[0.16813531]]),
 array([[0.08098516]]),
 array([[0.27707131]]),
 array([[0.23453854]]),
 array([[0.14502604]]),
 array([[0.08820113]]),
 array([[0.1447596]]),
 array([[0.06984303]]),
 array([[0.20221863]]),
 array([[0.20825463]]),
 array([[0.21105287]]),
 array([[0.095667]]),
 array([[0.17316075]]),
 array([[0.20753011]]),
 array([[0.19142226]]),
 array([[0.14366824]]),
 array([[0.23165287]]),
 array([[0.23829356]]),
 array([[0.20366334]]),
 array([[0.12492304]]),
 array([[0.17056206]]),
 array([[0.05692829]]),
 array([[0.11500384]]),
 array([[0.22683301]]),
 array([[0.15546154]]),
 array([[0.10531258]]),
 array([[0.27575093]]),
 array([[0.18629861]]),
 array([[0.10170004]]),
 array([[0.11510593]]),
 array([[0.19293849]]),
 array([[0.14002019]]),
 array([[0.24490388]]),
 array([[0.21453719]]),
 array([[0.15315079]]),
 array([[0.11155279]]),
 array([[0.1010064]]),
 array([[0.13183695]]),
 array([[0.16477656]]),
 array([[0.13681288]]),
 array([[0.11922947]]),
 array([[0.11315864]]),
 array([[0.16797743]]),
 array([[0.18547686]]),
 array([[0.10440564]]),
 array([[0.29491332]]),
 array([[0.14021027]]),
 array([[0.16161068]]),
 array([[0.12235404]]),
 array([[0.11267529]]),
 array([[0.15719567]]),
 array([[0.14507445]]),
 array([[0.20194323]]),
 array([[0.22668073]]),
 array([[0.1334028]]),
 array([[0.20299236]]),
 array([[0.1856669]]),
 array([[0.11901422]]),
 array([[0.20611508]]),
 array([[0.06735424]]),
 array([[0.16392915]]),
 array([[0.24295012]]),
 array([[0.06573512]]),
 array([[0.17683677]]),
 array([[0.16498767]]),
 array([[0.17337812]]),
 array([[0.13357892]]),
 array([[0.23450214]]),
 array([[0.1112853]]),
 array([[0.13669132]]),
 array([[0.10080662]]),
 array([[0.12549946]]),
 array([[0.16671635]]),
 array([[0.20736099]]),
 array([[0.17021951]]),
 array([[0.21437929]]),
 array([[0.19690401]]),
 array([[0.15968716]]),
 array([[0.12090894]]),
 array([[0.20554967]]),
 array([[0.08066303]]),
 array([[0.25535231]]),
 array([[0.19173653]]),
 array([[0.24932917]]),
 array([[0.14796039]]),
 array([[0.23206404]]),
 array([[0.1476251]]),
 array([[0.2367784]]),
 array([[0.14932289]]),
 array([[0.1811903]]),
 array([[0.15051295]]),
 array([[0.2971823]]),
 array([[0.1079659]]),
 array([[0.09011155]]),
 array([[0.14681604]]),
 array([[0.15572043]]),
 array([[0.17624743]]),
 array([[0.12241404]]),
 array([[0.23917177]]),
 array([[0.16193957]]),
 array([[0.18206894]]),
 array([[0.17538232]]),
 array([[0.13511315]]),
 array([[0.23399502]]),
 array([[0.23027218]]),
 array([[0.19254327]]),
 array([[0.15099805]]),
 array([[0.1566949]]),
 array([[0.10182256]]),
 array([[0.212924]]),
 array([[0.11766197]]),
 array([[0.12173562]]),
 array([[0.18508613]]),
 array([[0.18518856]]),
 array([[0.12567503]]),
 array([[0.12732505]]),
 array([[0.10252262]]),
 array([[0.14062508]]),
 array([[0.18689895]]),
 array([[0.10587268]]),
 array([[0.23368198]]),
 array([[0.12866863]]),
 array([[0.1580198]]),
 array([[0.13200776]]),
 array([[0.19254327]]),
 array([[0.15005208]]),
 array([[0.183918]]),
 array([[0.25466214]]),
 array([[0.14313332]]),
 array([[0.10415672]]),
 array([[0.13275696]]),
 array([[0.11408287]]),
 array([[0.06846168]]),
 array([[0.15923052]]),
 array([[0.12352356]]),
 array([[0.19164943]]),
 array([[0.17523399]]),
 array([[0.30435644]]),
 array([[0.10837211]]),
 array([[0.12144941]]),
 array([[0.17844806]]),
 array([[0.2005986]]),
 array([[0.07266441]]),
 array([[0.18664511]]),
 array([[0.10672697]]),
 array([[0.19617449]]),
 array([[0.27956613]]),
 array([[0.26431002]]),
 array([[0.20199004]]),
 array([[0.18440667]]),
 array([[0.13744601]]),
 array([[0.15531034]]),
 array([[0.24949694]]),
 array([[0.17337812]]),
 array([[0.22830462]]),
 array([[0.10965819]]),
 array([[0.25978213]]),
 array([[0.11240363]]),
 array([[0.28212584]]),
 array([[0.1371642]]),
 array([[0.157315]]),
 array([[0.18846484]]),
 array([[0.21817925]]),
 array([[0.29760621]]),
 array([[0.19877675]]),
 array([[0.13026402]]),
 array([[0.11801282]]),
 array([[0.26331508]]),
 array([[0.21711185]]),
 array([[0.33311765]]),
 array([[0.18187902]]),
 array([[0.20241782]]),
 array([[0.23113612]]),
 array([[0.18945731]]),
 array([[0.21575521]]),
 array([[0.20872061]]),
 array([[0.3280771]]),
 array([[0.27672011]]),
 array([[0.21527183]]),
 array([[0.13118095]]),
 array([[0.14629303]]),
 array([[0.20962306]]),
 array([[0.21615777]]),
 array([[0.10984312]]),
 array([[0.20290293]]),
 array([[0.12173168]]),
 array([[0.08487018]]),
 array([[0.15800211]]),
 array([[0.10393922]]),
 array([[0.23637177]]),
 array([[0.28813973]]),
 array([[0.1712142]]),
 array([[0.19667824]]),
 array([[0.13568078]]),
 array([[0.15005596]]),
 array([[0.14239225]]),
 array([[0.31847199]]),
 array([[0.21732014]]),
 array([[0.12964287]]),
 array([[0.31836481]]),
 array([[0.23769618]]),
 array([[0.22425442]]),
 array([[0.12428484]]),
 array([[0.22530536]]),
 array([[0.2062025]]),
 array([[0.12410892]]),
 array([[0.20507352]]),
 array([[0.06859233]]),
 array([[0.17752455]]),
 array([[0.1122342]]),
 array([[0.19805395]]),
 array([[0.19747351]]),
 array([[0.21097969]]),
 array([[0.19056851]]),
 array([[0.23758365]]),
 array([[0.1703951]]),
 array([[0.15857549]]),
 array([[0.20571522]]),
 array([[0.13095568]]),
 array([[0.13376765]]),
 array([[0.08807165]]),
 array([[0.15905227]]),
 array([[0.17707516]]),
 array([[0.13066823]]),
 array([[0.14283336]]),
 array([[0.25651078]]),
 array([[0.2038366]]),
 array([[0.22310161]]),
 array([[0.18475354]]),
 array([[0.14565024]]),
 array([[0.13937038]]),
 array([[0.12594739]]),
 array([[0.1229175]]),
 array([[0.18778627]]),
 array([[0.125645]]),
 array([[0.2569698]]),
 array([[0.22086305]]),
 array([[0.14643317]]),
 array([[0.21297957]]),
 array([[0.18692418]]),
 array([[0.18104087]]),
 array([[0.15748143]]),
 array([[0.10976156]]),
 array([[0.11230273]]),
 array([[0.22864706]]),
 array([[0.17463711]]),
 array([[0.15763402]]),
 array([[0.12611832]]),
 array([[0.2068957]]),
 array([[0.18501572]]),
 array([[0.10817991]]),
 array([[0.21541626]]),
 array([[0.22868359]]),
 array([[0.11170272]]),
 array([[0.1772528]]),
 array([[0.09894429]]),
 array([[0.15221075]]),
 array([[0.28267608]]),
 array([[0.20343877]]),
 array([[0.11214791]]),
 array([[0.11280964]]),
 array([[0.19957631]]),
 array([[0.35761918]]),
 array([[0.25306116]]),
 array([[0.10598783]]),
 array([[0.20120907]]),
 array([[0.09214418]]),
 array([[0.06276912]]),
 array([[0.08952029]]),
 array([[0.12644869]]),
 array([[0.18867756]]),
 array([[0.12275842]]),
 array([[0.17295664]]),
 array([[0.182431]]),
 array([[0.16716984]]),
 array([[0.17911314]]),
 array([[0.09963571]]),
 array([[0.08356248]]),
 array([[0.17867501]]),
 array([[0.12257657]]),
 array([[0.19440269]]),
 array([[0.14438324]]),
 array([[0.21765585]]),
 array([[0.08061093]]),
 array([[0.1150577]]),
 array([[0.10158886]]),
 array([[0.19526973]]),
 array([[0.14086706]]),
 array([[0.24299915]]),
 array([[0.17867401]]),
 array([[0.08614837]]),
 array([[0.14182597]]),
 array([[0.21625806]]),
 array([[0.14271898]]),
 array([[0.22959061]]),
 array([[0.17730522]]),
 array([[0.08998997]]),
 array([[0.22901811]]),
 array([[0.15779002]]),
 array([[0.1619244]]),
 array([[0.23277173]]),
 array([[0.17667319]]),
 array([[0.10356376]]),
 array([[0.13227002]]),
 array([[0.10275025]]),
 array([[0.07073027]]),
 array([[0.24636598]]),
 array([[0.21389428]]),
 array([[0.21612185]]),
 array([[0.16215048]]),
 array([[0.28605954]]),
 array([[0.13982892]]),
 array([[0.32114709]]),
 array([[0.12561294]]),
 array([[0.0963557]]),
 array([[0.18937442]]),
 array([[0.32196596]]),
 array([[0.09788832]]),
 array([[0.15654892]]),
 array([[0.23248072]]),
 array([[0.15043114]]),
 array([[0.14257566]]),
 array([[0.09370426]]),
 array([[0.14602555]]),
 array([[0.20137289]]),
 array([[0.26003305]]),
 array([[0.31446499]]),
 array([[0.20550298]]),
 array([[0.09272189]]),
 array([[0.15163286]]),
 array([[0.16437431]]),
 array([[0.1619806]]),
 array([[0.24128288]]),
 array([[0.1465732]]),
 array([[0.12859893]]),
 array([[0.36222997]]),
 array([[0.17110877]]),
 array([[0.10882144]]),
 array([[0.10320433]]),
 array([[0.05203404]]),
 array([[0.22247994]]),
 array([[0.1859346]]),
 array([[0.30979771]]),
 array([[0.10949828]]),
 array([[0.13172034]]),
 array([[0.23303112]]),
 array([[0.1427378]]),
 array([[0.17404068]]),
 array([[0.16726774]]),
 array([[0.12034678]]),
 array([[0.13252191]]),
 array([[0.17573191]]),
 array([[0.18821435]]),
 array([[0.30925343]]),
 array([[0.20952909]]),
 array([[0.17754973]]),
 array([[0.10318731]]),
 array([[0.1364612]]),
 array([[0.10801958]]),
 array([[0.15389266]]),
 array([[0.16277295]]),
 array([[0.22054977]]),
 array([[0.12149531]]),
 array([[0.10023966]]),
 array([[0.10103693]]),
 array([[0.17444216]]),
 array([[0.15172833]]),
 array([[0.20115459]]),
 array([[0.09152473]]),
 array([[0.14779606]]),
 array([[0.10490108]]),
 array([[0.1142709]]),
 array([[0.07407733]]),
 array([[0.1056754]]),
 array([[0.09566122]]),
 array([[0.09978277]]),
 array([[0.13333736]]),
 array([[0.11875781]]),
 array([[0.09773801]]),
 array([[0.09787376]]),
 array([[0.07998603]]),
 array([[0.07775103]]),
 array([[0.11513224]]),
 array([[0.08373432]]),
 array([[0.1007562]]),
 array([[0.14444063]]),
 array([[0.08075553]]),
 array([[0.07958922]]),
 array([[0.07769656]]),
 array([[0.09710304]]),
 array([[0.09783533]]),
 array([[0.08201517]]),
 array([[0.21095305]]),
 array([[0.35609196]]),
 array([[0.17849324]]),
 array([[0.22774789]]),
 array([[0.12767824]]),
 array([[0.09113284]]),
 array([[0.08640234]]),
 array([[0.09776644]]),
 array([[0.06804125]]),
 array([[0.07619272]]),
 array([[0.09289398]]),
 array([[0.2610395]]),
 array([[0.16262122]]),
 array([[0.20474689]]),
 array([[0.13674993]]),
 array([[0.16218243]]),
 array([[0.08265252]]),
 array([[0.26653906]]),
 array([[0.12145484]]),
 array([[0.10708564]]),
 array([[0.09615684]]),
 array([[0.14059678]]),
 array([[0.08879296]]),
 array([[0.10608232]]),
 array([[0.1761057]]),
 array([[0.09095708]]),
 array([[0.15601432]]),
 array([[0.15503478]]),
 array([[0.13346366]]),
 array([[0.15934423]]),
 array([[0.09152142]]),
 array([[0.13678922]]),
 array([[0.28006901]]),
 array([[0.07365251]]),
 array([[0.09713597]]),
 array([[0.07770745]]),
 array([[0.17090821]]),
 array([[0.08649835]]),
 array([[0.27600695]]),
 array([[0.10373005]]),
 array([[0.1343245]]),
 array([[0.20736408]]),
 array([[0.08511204]]),
 array([[0.08986979]]),
 array([[0.08835199]]),
 array([[0.08308143]]),
 array([[0.07833712]]),
 array([[0.08378272]]),
 array([[0.08955194]]),
 array([[0.18604621]]),
 array([[0.07218026]]),
 array([[0.19523441]]),
 array([[0.21225083]]),
 array([[0.16514533]]),
 array([[0.11616154]]),
 array([[0.11500319]]),
 array([[0.0668238]]),
 array([[0.11992106]]),
 array([[0.27688397]]),
 array([[0.15037255]]),
 array([[0.29219337]]),
 array([[0.1232374]]),
 array([[0.1174475]]),
 array([[0.10236083]]),
 array([[0.26461445]]),
 array([[0.08282494]]),
 array([[0.21783997]]),
 array([[0.10531792]]),
 array([[0.18634325]]),
 array([[0.14121138]]),
 array([[0.14316408]]),
 array([[0.08297073]]),
 array([[0.19527659]]),
 array([[0.13555783]]),
 array([[0.20044539]]),
 array([[0.17276779]]),
 array([[0.09496282]]),
 array([[0.078542]]),
 array([[0.11398877]]),
 array([[0.09831125]]),
 array([[0.10677988]]),
 array([[0.06299064]]),
 array([[0.11856355]]),
 array([[0.17441006]]),
 array([[0.09579061]]),
 array([[0.08278676]]),
 array([[0.169496]]),
 array([[0.08117429]]),
 array([[0.2007994]]),
 array([[0.06589025]]),
 array([[0.13939163]]),
 array([[0.05775804]]),
 array([[0.19411555]]),
 array([[0.14767355]]),
 array([[0.1194549]]),
 array([[0.13299366]]),
 array([[0.14626675]]),
 array([[0.21473116]]),
 array([[0.06220395]]),
 array([[0.14080401]]),
 array([[0.11369123]]),
 array([[0.18575398]]),
 array([[0.10538852]]),
 array([[0.085275]]),
 array([[0.20211653]]),
 array([[0.12551736]]),
 array([[0.09001787]]),
 array([[0.09633429]]),
 array([[0.21204558]]),
 array([[0.13589468]]),
 array([[0.09114515]]),
 array([[0.09887622]]),
 array([[0.1245744]]),
 array([[0.08674259]]),
 array([[0.13265326]]),
 array([[0.10545566]]),
 array([[0.10285947]]),
 array([[0.08533137]]),
 array([[0.16813531]]),
 array([[0.10680406]]),
 array([[0.11837497]]),
 array([[0.13037574]]),
 array([[0.09154931]]),
 array([[0.08570766]]),
 array([[0.17196701]]),
 array([[0.25324187]]),
 array([[0.11584734]]),
 array([[0.08203644]]),
 array([[0.12652099]]),
 array([[0.26807622]]),
 array([[0.09128095]]),
 array([[0.10560213]]),
 array([[0.20774808]]),
 array([[0.20221863]]),
 array([[0.14401599]]),
 array([[0.14876187]]),
 array([[0.15528697]]),
 array([[0.06996377]]),
 array([[0.14834147]]),
 array([[0.08359627]]),
 array([[0.19448042]]),
 array([[0.11396851]]),
 array([[0.10465717]]),
 array([[0.09821246]]),
 array([[0.09392674]]),
 array([[0.11407695]]),
 array([[0.08907252]]),
 array([[0.0872157]]),
 array([[0.18584215]]),
 array([[0.17124172]]),
 array([[0.09369519]]),
 array([[0.07321326]]),
 array([[0.11336056]]),
 array([[0.19363193]]),
 array([[0.13904256]]),
 array([[0.25535231]]),
 array([[0.12449674]]),
 array([[0.22683301]]),
 array([[0.14547499]]),
 array([[0.14780505]]),
 array([[0.15546154]]),
 array([[0.08223512]]),
 array([[0.19500213]]),
 array([[0.17122726]]),
 array([[0.10259877]]),
 array([[0.23829356]]),
 array([[0.21678588]]),
 array([[0.11601125]]),
 array([[0.10074044]]),
 array([[0.17876828]]),
 array([[0.08995474]]),
 array([[0.10024285]]),
 array([[0.07237942]]),
 array([[0.14208802]]),
 array([[0.16767098]]),
 array([[0.0965213]]),
 array([[0.11766197]]),
 array([[0.14066691]]),
 array([[0.23368198]]),
 array([[0.20397957]]),
 array([[0.2367784]]),
 array([[0.23917177]]),
 array([[0.23399502]]),
 array([[0.24932917]]),
 array([[0.24295012]]),
 array([[0.12866395]]),
 array([[0.23165287]]),
 array([[0.1333673]]),
 array([[0.09072876]]),
 array([[0.11249495]]),
 array([[0.13064981]]),
 array([[0.32678554]]),
 array([[0.07425626]]),
 array([[0.14347984]]),
 array([[0.06808598]]),
 array([[0.09792205]]),
 array([[0.20194323]]),
 array([[0.18689895]]),
 array([[0.06901688]]),
 array([[0.08718848]]),
 array([[0.18518856]]),
 array([[0.23206404]]),
 array([[0.17316075]]),
 array([[0.07165713]]),
 array([[0.20753011]]),
 array([[0.07176075]]),
 array([[0.14062508]]),
 array([[0.17337812]]),
 array([[0.25978213]]),
 array([[0.22251748]]),
 array([[0.27956613]]),
 array([[0.28212584]]),
 array([[0.16671635]]),
 array([[0.17683677]]),
 array([[0.1371642]]),
 array([[0.22668073]]),
 array([[0.21105287]]),
 array([[0.19142226]]),
 array([[0.12984834]]),
 array([[0.21453719]]),
 array([[0.14906074]]),
 array([[0.09975975]]),
 array([[0.2971823]]),
 array([[0.10098485]]),
 array([[0.19293849]]),
 array([[0.10371905]]),
 array([[0.07204783]]),
 array([[0.14566247]]),
 array([[0.13788999]]),
 array([[0.22134217]]),
 array([[0.08404671]]),
 array([[0.19876087]]),
 array([[0.09076027]]),
 array([[0.16477656]]),
 array([[0.13211187]]),
 array([[0.17567546]]),
 array([[0.14932289]]),
 array([[0.09927581]]),
 array([[0.08974725]]),
 array([[0.07226813]]),
 array([[0.08572048]]),
 array([[0.10432437]]),
 array([[0.13200776]]),
 array([[0.11543654]]),
 array([[0.12277815]]),
 array([[0.13169982]]),
 array([[0.12820876]]),
 array([[0.10454924]]),
 array([[0.11339995]]),
 array([[0.28163431]]),
 array([[0.08951351]]),
 array([[0.19173653]]),
 array([[0.22192641]]),
 array([[0.09086478]]),
 array([[0.14313332]]),
 array([[0.25864334]]),
 array([[0.11724253]]),
 array([[0.20193939]]),
 array([[0.15418865]]),
 array([[0.14998499]]),
 array([[0.10271874]]),
 array([[0.12282681]]),
 array([[0.16862749]]),
 array([[0.09054608]]),
 array([[0.17070361]]),
 array([[0.18664511]]),
 array([[0.1585078]]),
 array([[0.18522227]]),
 array([[0.09188522]]),
 array([[0.20199004]]),
 array([[0.06901498]]),
 array([[0.21329735]]),
 array([[0.07931464]]),
 array([[0.13237902]]),
 array([[0.20836784]]),
 array([[0.10208617]]),
 array([[0.18013356]]),
 array([[0.11373015]]),
 array([[0.09792205]]),
 array([[0.11012582]]),
 array([[0.20299236]]),
 array([[0.07859623]]),
 array([[0.14148727]]),
 array([[0.14885016]]),
 array([[0.13511315]]),
 array([[0.1136988]]),
 array([[0.25466214]]),
 array([[0.0824234]]),
 array([[0.08704297]]),
 array([[0.12909282]]),
 array([[0.12893045]]),
 array([[0.18508613]]),
 array([[0.10337645]]),
 array([[0.08116472]]),
 array([[0.10863522]]),
 array([[0.09219741]]),
 array([[0.11070184]]),
 array([[0.20142948]]),
 array([[0.19406005]]),
 array([[0.10090169]]),
 array([[0.18206894]]),
 array([[0.17337812]]),
 array([[0.13176146]]),
 array([[0.18230683]]),
 array([[0.09323529]]),
 array([[0.07905666]]),
 array([[0.09602748]]),

In [161]:
df.rating

0       3.7
1       4.0
2       4.0
3       NaN
4       NaN
       ...
5497    NaN
5498    NaN
5499    NaN
5500    NaN
5501    5.0
Name: rating, Length: 5502, dtype: float64

In [162]:
top = sorted(range(len(output3)), key=lambda i: output3[i], reverse=True)[:100]
list_scores = [output3[i][0][0] for i in top]
cv=get_recommendation(top, df, list_scores)
cv

,positionName,company,location,description,score,JobID
0,Python Machine Learning Engineer,Vingsfire HRIM Pvt Ltd,"Madurai, Tamil Nadu",Role : Senior Python DeveloperExperience: 5+ Y...,0.36223,473.0
1,MACHINE LEARNING ENGINEER,Amanzi Technologies,"Noida, Uttar Pradesh",Amanzi Technologies Pvt. Ltd. ...,0.357619,400.0
2,MACHINE LEARNING ENGINEER,Amanzi Technologies,"Noida, Uttar Pradesh",Amanzi Technologies Pvt. Ltd. ...,0.357619,920.0
3,Data Scientist (India Remote),Token Metrics,"Bengaluru, Karnataka",Token Metrics is searching for a highly capabl...,0.356092,74.0
4,Data Scientist (India Remote),Token Metrics,"Bengaluru, Karnataka",Token Metrics is searching for a highly capabl...,0.356092,531.0
...,...,...,...,...,...,...
95,Lead Machine Learning Firmware Test Engineer,Axiado,"Hyderabad, Telangana",Company Description Axiado is an AI-enhanced ...,0.237696,872.0
96,Machine Learning,Think Future Technologies,"Gurgaon, Haryana",Exp: 2 + Years Location: Gurgaon/ Remote Ski...,0.237584,352.0
97,Machine Learning Engineer,Apple,"Bengaluru, Karnataka","Summary Posted: Dec 7, 2022 ...",0.236778,225.0
98,Machine Learning Engineer,Apple,"Bengaluru, Karnataka","Summary Posted: Dec 7, 2022 ...",0.236778,710.0
99,Data Scientist,Ergode IT Services Pvt. ltd.,"Mumbai, Maharashtra",Role Description - (Mumbai Based and Immediate...,0.236372,327.0

In [163]:
cv.description[1]

'Amanzi Technologies Pvt. Ltd.                              Permanent                              Noida                              Posted 3 weeks ago                          Out of the box solution          Responsibilities:      Designing and developing machine learning and deep learning systems.    Running machine learning tests and experiments.    Implementing appropriate ML algorithms.        Job brief:   We are looking for a Machine Learning (ML) Engineer to help us create artificial intelligence products.   Machine Learning Engineer responsibilities include creating machine learning models and retraining systems. To do this job successfully, you need exceptional skills in statistics and programming. If you also have knowledge of data science and software engineering, we’d like to meet you.   Your ultimate goal will be to shape and build efficient self-learning applications.   Responsibilities:      Study and transform data science prototypes.    Design machine learning systemsResearch and implement appropriate ML algorithms and tools.    Develop machine learning applications according to requirements.    Select appropriate datasets and data representation methodsRun machine learning tests and experiments.    Perform statistical analysis and fine-tuning using test resultsTrain and retrain systems when necessary.    Extend existing ML libraries and frameworks.    Keep abreast of developments in the field        Mandatory skills:      Bachelor’s degree in computer science, data science, mathematics, or a related field. (B.E / MCA / B. tech / P. hd).    4-7 years of experience as a machine learning engineer.    Extensive knowledge of ML frameworks, libraries, data structures, data modelling, and software architecture.    In-depth knowledge of mathematics, statistics, and algorithms.    Proficiency with a deep learning framework such as TensorFlow or Keras.    Proficiency with Python(Mandate) and basic libraries for machine learning such as scikit-learn and pandas.    Ability to select hardware to run an ML model with the required latency.    Proficiency in Artificial neural networks, RNN, LSTM.    Hands-on Autoencoders, GAN’s, Convolution neural networks and Deep learning models.    Experience with at least one cloud provider solution (AWS, GCP, Azure).        Job Features                     Job Category                 Information Technology'

## TfidfVectorizer + NearestNeighbors

In [164]:
from sklearn.neighbors import NearestNeighbors

def KNN(scraped_data, cv):
    tfidf_vectorizer = TfidfVectorizer(stop_words='english')

    
    KNN = NearestNeighbors(n_neighbors=100,p=2)
    KNN.fit(tfidf_vectorizer.fit_transform(scraped_data))
#     NNs = KNN.kneighbors(tfidf_vectorizer.transform(cv), return_distance=True)
    NNs = KNN.kneighbors(tfidf_vectorizer.transform(cv))
    top = NNs[1][0][1:]
    index_score = NNs[0][0][1:]

    knn = get_recommendation(top, df, index_score)
    return knn

knn = KNN(df['All'], df2['All'])
knn

,positionName,company,location,description,score,JobID
0,Data Scientist,Chubb INA Holdings Inc.,"Bengaluru, Karnataka",Job Requirements Responsibilities Work with b...,1.2503,91.0
1,Data Science - Knowledge Graph,Chubb INA Holdings Inc.,"Bengaluru, Karnataka",Work Experience Work with business partners gl...,1.25192,95.0
2,"Manager MLOps, Data Science",Mondelēz International,"Mumbai, Maharashtra",Job Description Are You Ready to Make It Hap...,1.25793,982.0
3,"Manager MLOps, Data Science",Mondelēz International,"Mumbai, Maharashtra",Job Description Are You Ready to Make It Hap...,1.25793,382.0
4,ASSOCIATE DEVOPS ENGINEER,SKS Enterpprise,"Chennai, Tamil Nadu",Position Name - Associate DevOps Engineer L...,1.26768,779.0
...,...,...,...,...,...,...
94,Deputy Manager-Aftermarket and Service (Data S...,Pratt & Whitney,"Bengaluru, Karnataka",Date Posted: +91-XXXXXXXXXX:00 Country: Indi...,1.31387,66.0
95,Data Science (NLP) Intern,Emplay Inc,Remote,"Job Title: NLP/Data Science InternStipend- 20,...",1.31466,430.0
96,Data Science and Business Analytics,Zotto Limited,"Delhi, Delhi",We are looking for a Data Scientist who will s...,1.31468,306.0
97,Lead Machine Learning Firmware Test Engineer,Axiado,"Hyderabad, Telangana",Company Description Axiado is an AI-enhanced ...,1.31532,338.0
98,Lead Machine Learning Firmware Test Engineer,Axiado,"Hyderabad, Telangana",Company Description Axiado is an AI-enhanced ...,1.31532,872.0

In [165]:

knn.to_csv('knn.csv', index=False)

In [166]:
cv

,positionName,company,location,description,score,JobID
0,Python Machine Learning Engineer,Vingsfire HRIM Pvt Ltd,"Madurai, Tamil Nadu",Role : Senior Python DeveloperExperience: 5+ Y...,0.36223,473.0
1,MACHINE LEARNING ENGINEER,Amanzi Technologies,"Noida, Uttar Pradesh",Amanzi Technologies Pvt. Ltd. ...,0.357619,400.0
2,MACHINE LEARNING ENGINEER,Amanzi Technologies,"Noida, Uttar Pradesh",Amanzi Technologies Pvt. Ltd. ...,0.357619,920.0
3,Data Scientist (India Remote),Token Metrics,"Bengaluru, Karnataka",Token Metrics is searching for a highly capabl...,0.356092,74.0
4,Data Scientist (India Remote),Token Metrics,"Bengaluru, Karnataka",Token Metrics is searching for a highly capabl...,0.356092,531.0
...,...,...,...,...,...,...
95,Lead Machine Learning Firmware Test Engineer,Axiado,"Hyderabad, Telangana",Company Description Axiado is an AI-enhanced ...,0.237696,872.0
96,Machine Learning,Think Future Technologies,"Gurgaon, Haryana",Exp: 2 + Years Location: Gurgaon/ Remote Ski...,0.237584,352.0
97,Machine Learning Engineer,Apple,"Bengaluru, Karnataka","Summary Posted: Dec 7, 2022 ...",0.236778,225.0
98,Machine Learning Engineer,Apple,"Bengaluru, Karnataka","Summary Posted: Dec 7, 2022 ...",0.236778,710.0
99,Data Scientist,Ergode IT Services Pvt. ltd.,"Mumbai, Maharashtra",Role Description - (Mumbai Based and Immediate...,0.236372,327.0

## Combined TFIDF, CV and KNN result together, to make a dataframe "final"

In [171]:
merge1 = knn[['JobID','positionName', 'score']].merge(TF[['JobID','score']], on= "JobID")

In [172]:
# merge1 = knn[['JobID','title', 'score']].merge(TF[['JobID','score']], on= "JobID")
# final = merge1.merge(cv[['JobID','score']], on = "JobID")
# final = final.rename(columns={"score_x": "KNN", "score_y": "TF-IDF","score": "CV"})
# final.head()a

final = merge1.merge(cv[['JobID','score']], on = "JobID")
final = final.rename(columns={"score_x": "KNN", "score_y": "TF-IDF","score": "CV"})
final.head()

   JobID                    positionName      KNN    TF-IDF        CV
0   91.0                  Data Scientist   1.2503  0.218374  0.304615
1   95.0  Data Science - Knowledge Graph  1.25192  0.216345  0.302467
2  779.0       ASSOCIATE DEVOPS ENGINEER  1.26768  0.196495  0.281634
3  400.0       MACHINE LEARNING ENGINEER  1.27042  0.193014  0.357619
4  920.0       MACHINE LEARNING ENGINEER   1.2705  0.192913  0.357619

In [173]:
final

,JobID,positionName,KNN,TF-IDF,CV
0,91.0,Data Scientist,1.2503,0.218374,0.304615
1,95.0,Data Science - Knowledge Graph,1.25192,0.216345,0.302467
2,779.0,ASSOCIATE DEVOPS ENGINEER,1.26768,0.196495,0.281634
3,400.0,MACHINE LEARNING ENGINEER,1.27042,0.193014,0.357619
4,920.0,MACHINE LEARNING ENGINEER,1.2705,0.192913,0.357619
5,54.0,Machine Learning Engineer,1.27331,0.18934,0.280069
6,562.0,Machine Learning Engineer,1.27331,0.18934,0.280069
7,183.0,Senior Data Scientist,1.2775,0.183991,0.294913
8,334.0,Data Scientist,1.28278,0.177236,0.318472
9,337.0,Data Scientist,1.28318,0.176724,0.318365
10,845.0,AVP-DEVOPS,1.28735,0.171368,0.271842
11,473.0,Python Machine Learning Engineer,1.28815,0.170334,0.36223
12,74.0,Data Scientist (India Remote),1.28919,0.168991,0.356092
13,531.0,Data Scientist (India Remote),1.28919,0.168991,0.356092
14,164.0,Python Data Science Trainer,1.29025,0.167627,0.275751
15,721.0,Automation Engineer,1.29304,0.164022,0.326786
16,711.0,Machine Learning Engineer,1.29328,0.163709,0.239172
17,236.0,Machine Learning Engineer,1.29334,0.163641,0.239172
18,541.0,AI Engineer_MLOPS_3 to 10 years,1.29397,0.162826,0.261039
19,3711.0,AI Engineer_MLOPS_3 to 10 years,1.29397,0.162826,0.261039
20,307.0,Data Science - Lead & Manager/Sr. Manager,1.29573,0.160545,0.333118
21,221.0,Machine Learning Engineer,1.29857,0.156863,0.249329
22,713.0,Machine Learning Engineer,1.29862,0.156797,0.249329
23,285.0,AI Tech Lead,1.29941,0.155763,0.26431
24,275.0,Senior Machine Learning Researcher,1.29981,0.155241,0.304356
25,752.0,Machine Learning Engineer,1.3005,0.154346,0.297182
26,1859.0,Machine Learning Engineer,1.30058,0.154244,0.297182
27,229.0,Machine Learning Engineer,1.30065,0.154158,0.297182
28,444.0,Data Science Engineer,1.30085,0.153891,0.246366
29,463.0,Machine Learning Engineer,1.30232,0.151976,0.260033
30,140.0,Data Scientist,1.303,0.151097,0.277071
31,225.0,Machine Learning Engineer,1.3037,0.150184,0.236778
32,710.0,Machine Learning Engineer,1.3037,0.150183,0.236778
33,284.0,Senior Machine Learning Engineer,1.30428,0.149428,0.279566
34,1970.0,Senior Machine Learning Engineer,1.30449,0.149152,0.279566
35,740.0,Senior Machine Learning Engineer,1.30449,0.149152,0.279566
36,327.0,Data Scientist,1.30494,0.148562,0.236372
37,450.0,Sr. Data Scientist,1.30596,0.14724,0.321147
38,305.0,Data Scientist,1.30698,0.145899,0.263315
39,741.0,SatSure Analytics - Machine Learning Engineer,1.30735,0.145413,0.282126
40,296.0,SatSure Analytics - Machine Learning Engineer,1.30735,0.145413,0.282126
41,1999.0,SatSure Analytics - Machine Learning Engineer,1.30735,0.145413,0.282126
42,294.0,Senior Machine Learning Engineer Opportunity A...,1.30772,0.144928,0.259782
43,738.0,Senior Machine Learning Engineer Opportunity A...,1.30776,0.144883,0.259782
44,547.0,Data Science Engineer,1.30804,0.144521,0.266539
45,33.0,Data Science Engineer,1.30804,0.144521,0.266539
46,199.0,Machine Learning Engineer,1.30986,0.142134,0.24295
47,714.0,Machine Learning Engineer,1.30986,0.142134,0.24295
48,78.0,Machine Learning Developer,1.31031,0.141546,0.257025
49,464.0,Machine Learning Intern,1.31086,0.14082,0.314465
50,871.0,Machine Learning Engineer (2-4 years),1.31352,0.137334,0.27672
51,315.0,Machine Learning Engineer (2-4 years),1.31352,0.137334,0.27672
52,373.0,AI/ML Engineer,1.31368,0.137119,0.25697
53,917.0,AI/ML Engineer,1.31368,0.137119,0.25697
54,338.0,Lead Machine Learning Firmware Test Engineer,1.31532,0.134965,0.237696
55,872.0,Lead Machine Learning Firmware Test Engineer,1.31532,0.134965,0.237696

In [174]:
# Scale it
from sklearn.preprocessing import MinMaxScaler
slr = MinMaxScaler()
final[["KNN", "TF-IDF", 'CV']] = slr.fit_transform(final[["KNN", "TF-IDF", 'CV']])

# Multiply by weights
final['KNN'] = (1-final['KNN'])/3
final['TF-IDF'] = final['TF-IDF']/3
final['CV'] = final['CV']/3
final['Final'] = final['KNN']+final['TF-IDF']+final['CV']
final.sort_values(by="Final", ascending=False)

,JobID,positionName,KNN,TF-IDF,CV,Final
0,91.0,Data Scientist,0.333333,0.333333,0.180742,0.847408
1,95.0,Data Science - Knowledge Graph,0.325020,0.325226,0.175051,0.825297
3,400.0,MACHINE LEARNING ENGINEER,0.230180,0.231985,0.321122,0.783286
4,920.0,MACHINE LEARNING ENGINEER,0.229775,0.231584,0.321122,0.782481
11,473.0,Python Machine Learning Engineer,0.139292,0.141347,0.333333,0.613972
2,779.0,ASSOCIATE DEVOPS ENGINEER,0.244245,0.245899,0.119877,0.610021
13,531.0,Data Scientist (India Remote),0.133951,0.135981,0.317077,0.587009
12,74.0,Data Scientist (India Remote),0.133951,0.135981,0.317077,0.587009
8,334.0,Data Scientist,0.166818,0.168930,0.217441,0.553188
9,337.0,Data Scientist,0.164773,0.166885,0.217157,0.548815
6,562.0,Machine Learning Engineer,0.215372,0.217304,0.115731,0.548408
5,54.0,Machine Learning Engineer,0.215372,0.217304,0.115731,0.548408
7,183.0,Senior Data Scientist,0.193869,0.195925,0.155046,0.544841
15,721.0,Automation Engineer,0.114221,0.116123,0.239459,0.469803
20,307.0,Data Science - Lead & Manager/Sr. Manager,0.100447,0.102225,0.256230,0.458902
10,845.0,AVP-DEVOPS,0.143409,0.145479,0.093943,0.382831
14,164.0,Python Data Science Trainer,0.128530,0.130531,0.104295,0.363356
24,275.0,Senior Machine Learning Researcher,0.079496,0.081030,0.180056,0.340582
37,450.0,Sr. Data Scientist,0.048011,0.049053,0.224526,0.321590
25,752.0,Machine Learning Engineer,0.075967,0.077454,0.161056,0.314476
26,1859.0,Machine Learning Engineer,0.075563,0.077044,0.161056,0.313662
27,229.0,Machine Learning Engineer,0.075225,0.076701,0.161056,0.312981
19,3711.0,AI Engineer_MLOPS_3 to 10 years,0.109478,0.111341,0.065332,0.286151
18,541.0,AI Engineer_MLOPS_3 to 10 years,0.109478,0.111341,0.065332,0.286151
49,464.0,Machine Learning Intern,0.022859,0.023399,0.206829,0.253086
23,285.0,AI Tech Lead,0.081553,0.083114,0.073994,0.238661
30,140.0,Data Scientist,0.063170,0.064468,0.107792,0.235430
16,711.0,Machine Learning Engineer,0.112980,0.114873,0.007416,0.235269
17,236.0,Machine Learning Engineer,0.112710,0.114601,0.007416,0.234726
33,284.0,Senior Machine Learning Engineer,0.056607,0.057798,0.114400,0.228805
34,1970.0,Senior Machine Learning Engineer,0.055522,0.056695,0.114400,0.226616
35,740.0,Senior Machine Learning Engineer,0.055522,0.056695,0.114400,0.226616
21,221.0,Machine Learning Engineer,0.085897,0.087513,0.034317,0.207728
22,713.0,Machine Learning Engineer,0.085637,0.087249,0.034317,0.207203
41,1999.0,SatSure Analytics - Machine Learning Engineer,0.040846,0.041754,0.121179,0.203778
40,296.0,SatSure Analytics - Machine Learning Engineer,0.040846,0.041754,0.121179,0.203778
39,741.0,SatSure Analytics - Machine Learning Engineer,0.040846,0.041754,0.121179,0.203778
29,463.0,Machine Learning Engineer,0.066629,0.067980,0.062666,0.197275
28,444.0,Data Science Engineer,0.074172,0.075634,0.026470,0.176275
38,305.0,Data Scientist,0.042749,0.043694,0.071359,0.157802
44,547.0,Data Science Engineer,0.037347,0.038188,0.079898,0.155433
45,33.0,Data Science Engineer,0.037347,0.038188,0.079898,0.155433
42,294.0,Senior Machine Learning Engineer Opportunity A...,0.038943,0.039815,0.062002,0.140760
43,738.0,Senior Machine Learning Engineer Opportunity A...,0.038766,0.039634,0.062002,0.140401
50,871.0,Machine Learning Engineer (2-4 years),0.009240,0.009468,0.106862,0.125569
51,315.0,Machine Learning Engineer (2-4 years),0.009240,0.009468,0.106862,0.125569
31,225.0,Machine Learning Engineer,0.059579,0.060819,0.001077,0.121475
32,710.0,Machine Learning Engineer,0.059574,0.060814,0.001077,0.121465
36,327.0,Data Scientist,0.053206,0.054339,0.000000,0.107545
48,78.0,Machine Learning Developer,0.025696,0.026297,0.054699,0.106693
47,714.0,Machine Learning Engineer,0.027998,0.028648,0.017423,0.074069
46,199.0,Machine Learning Engineer,0.027998,0.028648,0.017423,0.074069
52,373.0,AI/ML Engineer,0.008398,0.008606,0.054554,0.071558
53,917.0,AI/ML Engineer,0.008398,0.008606,0.054554,0.071558
54,338.0,Lead Machine Learning Firmware Test Engineer,0.000000,0.000000,0.003508,0.003508
55,872.0,Lead Machine Learning Firmware Test Engineer,0.000000,0.000000,0.003508,0.003508

In [176]:
# final.to_csv('final.csv', index=False)
final2 = final.sort_values(by="Final", ascending=False).copy()
final2

,JobID,positionName,KNN,TF-IDF,CV,Final
0,91.0,Data Scientist,0.333333,0.333333,0.180742,0.847408
1,95.0,Data Science - Knowledge Graph,0.325020,0.325226,0.175051,0.825297
3,400.0,MACHINE LEARNING ENGINEER,0.230180,0.231985,0.321122,0.783286
4,920.0,MACHINE LEARNING ENGINEER,0.229775,0.231584,0.321122,0.782481
11,473.0,Python Machine Learning Engineer,0.139292,0.141347,0.333333,0.613972
2,779.0,ASSOCIATE DEVOPS ENGINEER,0.244245,0.245899,0.119877,0.610021
13,531.0,Data Scientist (India Remote),0.133951,0.135981,0.317077,0.587009
12,74.0,Data Scientist (India Remote),0.133951,0.135981,0.317077,0.587009
8,334.0,Data Scientist,0.166818,0.168930,0.217441,0.553188
9,337.0,Data Scientist,0.164773,0.166885,0.217157,0.548815
6,562.0,Machine Learning Engineer,0.215372,0.217304,0.115731,0.548408
5,54.0,Machine Learning Engineer,0.215372,0.217304,0.115731,0.548408
7,183.0,Senior Data Scientist,0.193869,0.195925,0.155046,0.544841
15,721.0,Automation Engineer,0.114221,0.116123,0.239459,0.469803
20,307.0,Data Science - Lead & Manager/Sr. Manager,0.100447,0.102225,0.256230,0.458902
10,845.0,AVP-DEVOPS,0.143409,0.145479,0.093943,0.382831
14,164.0,Python Data Science Trainer,0.128530,0.130531,0.104295,0.363356
24,275.0,Senior Machine Learning Researcher,0.079496,0.081030,0.180056,0.340582
37,450.0,Sr. Data Scientist,0.048011,0.049053,0.224526,0.321590
25,752.0,Machine Learning Engineer,0.075967,0.077454,0.161056,0.314476
26,1859.0,Machine Learning Engineer,0.075563,0.077044,0.161056,0.313662
27,229.0,Machine Learning Engineer,0.075225,0.076701,0.161056,0.312981
19,3711.0,AI Engineer_MLOPS_3 to 10 years,0.109478,0.111341,0.065332,0.286151
18,541.0,AI Engineer_MLOPS_3 to 10 years,0.109478,0.111341,0.065332,0.286151
49,464.0,Machine Learning Intern,0.022859,0.023399,0.206829,0.253086
23,285.0,AI Tech Lead,0.081553,0.083114,0.073994,0.238661
30,140.0,Data Scientist,0.063170,0.064468,0.107792,0.235430
16,711.0,Machine Learning Engineer,0.112980,0.114873,0.007416,0.235269
17,236.0,Machine Learning Engineer,0.112710,0.114601,0.007416,0.234726
33,284.0,Senior Machine Learning Engineer,0.056607,0.057798,0.114400,0.228805
34,1970.0,Senior Machine Learning Engineer,0.055522,0.056695,0.114400,0.226616
35,740.0,Senior Machine Learning Engineer,0.055522,0.056695,0.114400,0.226616
21,221.0,Machine Learning Engineer,0.085897,0.087513,0.034317,0.207728
22,713.0,Machine Learning Engineer,0.085637,0.087249,0.034317,0.207203
41,1999.0,SatSure Analytics - Machine Learning Engineer,0.040846,0.041754,0.121179,0.203778
40,296.0,SatSure Analytics - Machine Learning Engineer,0.040846,0.041754,0.121179,0.203778
39,741.0,SatSure Analytics - Machine Learning Engineer,0.040846,0.041754,0.121179,0.203778
29,463.0,Machine Learning Engineer,0.066629,0.067980,0.062666,0.197275
28,444.0,Data Science Engineer,0.074172,0.075634,0.026470,0.176275
38,305.0,Data Scientist,0.042749,0.043694,0.071359,0.157802
44,547.0,Data Science Engineer,0.037347,0.038188,0.079898,0.155433
45,33.0,Data Science Engineer,0.037347,0.038188,0.079898,0.155433
42,294.0,Senior Machine Learning Engineer Opportunity A...,0.038943,0.039815,0.062002,0.140760
43,738.0,Senior Machine Learning Engineer Opportunity A...,0.038766,0.039634,0.062002,0.140401
50,871.0,Machine Learning Engineer (2-4 years),0.009240,0.009468,0.106862,0.125569
51,315.0,Machine Learning Engineer (2-4 years),0.009240,0.009468,0.106862,0.125569
31,225.0,Machine Learning Engineer,0.059579,0.060819,0.001077,0.121475
32,710.0,Machine Learning Engineer,0.059574,0.060814,0.001077,0.121465
36,327.0,Data Scientist,0.053206,0.054339,0.000000,0.107545
48,78.0,Machine Learning Developer,0.025696,0.026297,0.054699,0.106693
47,714.0,Machine Learning Engineer,0.027998,0.028648,0.017423,0.074069
46,199.0,Machine Learning Engineer,0.027998,0.028648,0.017423,0.074069
52,373.0,AI/ML Engineer,0.008398,0.008606,0.054554,0.071558
53,917.0,AI/ML Engineer,0.008398,0.008606,0.054554,0.071558
54,338.0,Lead Machine Learning Firmware Test Engineer,0.000000,0.000000,0.003508,0.003508
55,872.0,Lead Machine Learning Firmware Test Engineer,0.000000,0.000000,0.003508,0.003508

In [179]:
# final2.merge(df, on="JobID")
final_df = df.merge(final2, on="id")
final_df

KeyError: 'id'